version: "3.8"

services:
  prometheus:
    image: "prom/prometheus:latest"
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - testnet

  grafana:
    image: "grafana/grafana-oss:latest"
    environment:
      - PROM_URL=http://prometheus:9090
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana:/etc/grafana/provisioning/
      - prometheus_data:/prometheus
    networks:
      - testnet

  blockgen:
    image: "committer-loadgen:latest"
    volumes:
      - ../config/config-blockgen.yaml:/config.yaml
      - ../scripts/blockgen.docker-entrypoint.sh:/docker-entrypoint.sh
    entrypoint: ./docker-entrypoint.sh
    ports:
      - "6997:6997"
    networks:
      - testnet

volumes:
  prometheus_data:

networks:
  testnet:
    name: test_default
    external: true

