language: go
go:
    - 1.20.3

services:
  - docker

cache:
    directories:
      - $HOME/.cache/go-build        # Cache the binaries
      - $HOME/gopath/pkg/mod         # Cache the Go modules

script:
    - make test
