language: go
go:
    - 1.20.3

services:
  - docker

cache:
    directories:
      - $HOME/.cache/go-build        # Cache the binaries
      - $HOME/gopath/pkg/mod         # Cache the Go modules

before_install:
  - scripts/install-protobuf.sh
  - go install golang.org/x/tools/cmd/goimports@latest
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.53.3
  # We pull the docker image before the tests to avoid timeouts in the test due to slow download time
  - docker pull yugabytedb/yugabyte:2.19.0.0-b190

script:
  - find . -name \*.go -not -name \*.pb.go -exec goimports -d -e {}\; | tee /dev/stderr | [ $(wc -c) -eq 0 ]
  - find . -name \*.go -not -name \*.pb.go -exec gofmt -d -e  {}\; | tee /dev/stderr | [ $(wc -c) -eq 0 ]
  - PATH="$HOME/bin:$PATH" make protos-blocktx
  - git diff | tee /dev/stderr | [ $(wc -c) -eq 0 ]
  - make test
