language: go
arch: amd64
virt: vm
os: linux
dist: focal
go:
  - 1.23.4

cache:
  directories:
    - $HOME/.cache/go-build # Cache the binaries
    - $HOME/gopath/pkg/mod # Cache the Go modules

services:
  - docker

stages:
  - lint
  - test

before_install:
  - export GO111MODULE=on
  - export GOPRIVATE=github.ibm.com
  - export DB_INSTANCE=local
  - git config --global url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.ibm.com".insteadOf "https://github.ibm.com"

install:
  # Start VCService database
  - scripts/get-and-start-$VCSERVICE_DB.sh

jobs:
  include:
    - stage: lint
      install:
        # Install dependencies
        - scripts/install-protobuf.sh
        - go install golang.org/x/tools/cmd/goimports@latest
        - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.61.0
      before_script:
        # Fetch main to only detect issues from changes to main
        - git fetch origin main:main
        # Apply formatting
        - find . -name \*.go -not -name \*.pb.go -exec goimports -d -e {} \; | tee /dev/stderr | [ $(wc -c) -eq 0 ]
        - find . -name \*.go -not -name \*.pb.go -exec gofmt -d -e  {} \; | tee /dev/stderr | [ $(wc -c) -eq 0 ]
        - PATH="$HOME/bin:$PATH" make protos-blocktx
      script:
        # Check if original code changed due to formatting
        - git diff | tee /dev/stderr | [ $(wc -c) -eq 0 ]
        # Run lint and test
        - make lint
    - stage: test
      name: Unit Tests (postgres)
      env: VCSERVICE_DB=postgres
      script: make test
    - stage: test
      name: Unit Tests (yugabyte)
      env: VCSERVICE_DB=yuga
      script: make test
    - stage: test
      name: Integration Tests (yugabyte)
      env: VCSERVICE_DB=yuga
      script: make integration-test
    - stage: test
      name: Build container images
      install: skip
      script: make build-test-node-image -j16
