coordinator-service:
  server:
    endpoint:
      host: ""
      port: 9001
  sign-verifier:
    server:
      - # server 1 configuration
        endpoint:
          host: "sigservice"
          port: 5001
  validator-committer:
    server:
      - # server 1 configuration
        endpoint:
          host: "vcservice"
          port: 6001
  dependency-graph:
    num-of-local-dep-constructors: 20
    waiting-txs-limit: 10000
    num-of-workers-for-global-dep-manager: 20
    per-channel-buffer-size-per-goroutine: 300
  monitoring:
    metrics:
      enable: true
      endpoint: :2110
logging:
  development: true
  enabled: true
  level: INFO

