OrdererOrgs:
  - Name: orderer
    Domain: orderer.org
    EnableNodeOUs: true
    Specs:
      - Hostname: raft0
        SANS:
          - 0.0.0.0
          - localhost
      - Hostname: raft1
        SANS:
          - 0.0.0.0
          - localhost
      - Hostname: raft2
        SANS:
          - 0.0.0.0
          - localhost
      - Hostname: raft3
        SANS:
          - 0.0.0.0
          - localhost
      - Hostname: raft4
        SANS:
          - 0.0.0.0
          - localhost

PeerOrgs:
  - Name: org1
    Domain: org1.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - 0.0.0.0
    Users:
      Count: 1
