orderer-submitter:
  channel-id: mychannel
  orderers:
    - localhost:7051
  prometheus:
    endpoint: :2112
  orderer-connection-profile: ./orderer-connection-profile.yaml
  messages: 5000000
  go-routines: 20
  message-size: 160
  signed-envelopes: false
  orderer-type: BFT