orderer-submitter:
  channel-id: mychannel
  orderers:
    - :7050
    - :7051
    - :7052
  prometheus:
    endpoint: :2114
  orderer-connection-profile: ./orderer-connection-profile.yaml
  messages: 10000
  go-routines: 20
  message-size: 160
  signed: true