all:
  vars:
    ansible_connection: ssh
    ansible_user: "{{lookup('env', 'USER')}}"

  children:
    services:
      vars:
        ansible_user: root
      hosts:
        machine1:
          ansible_host: tokentestbed1.sl.cloud9.ibm.com
        machine2:
          ansible_host: tokentestbed2.sl.cloud9.ibm.com
        machine3:
          ansible_host: tokentestbed3.sl.cloud9.ibm.com
        machine4:
          ansible_host: tokentestbed4.sl.cloud9.ibm.com
        machine5:
          ansible_host: tokentestbed5.sl.cloud9.ibm.com
        machine6:
          ansible_host: tokentestbed6.sl.cloud9.ibm.com
        machine7:
          ansible_host: tokentestbed7.sl.cloud9.ibm.com
        machine8:
          ansible_host: tokentestbed8.sl.cloud9.ibm.com
        machine9:
          ansible_host: tokentestbed9.sl.cloud9.ibm.com
        machine10:
          ansible_host: tokentestbed10.sl.cloud9.ibm.com
        machine11:
          ansible_host: tokentestbed11.sl.cloud9.ibm.com
        machine12:
          ansible_host: tokentestbed12.sl.cloud9.ibm.com
        machine13:
          ansible_host: tokentestbed13.sl.cloud9.ibm.com
        machine14:
          ansible_host: tokentestbed14.sl.cloud9.ibm.com
        machine15:
          ansible_host: tokentestbed15.sl.cloud9.ibm.com
        machine16:
          ansible_host: tokentestbed16.sl.cloud9.ibm.com
