all:
  vars:
    ansible_connection: ssh
    ansible_user: "{{lookup('env', 'USER')}}"
    binary_dir: /root/bin/
    top_config_dir: /root/config
    config_dir: "{{top_config_dir}}"
    os: linux
    prometheus_exporter_port: 2112

  children:
    services:
      vars:
        ansible_user: root
      children:

        coordinators:
          vars:
            service_port: 5002
            config: config-coordinator.yaml
          hosts:
            coordinator-machine:
              inherit_endorser: endorser-1 # Used for setting the sig verification key
              config_dir: "{{top_config_dir}}/coordinator"
              prometheus_exporter_port: 2113
              ansible_host: tokentestbed10.sl.cloud9.ibm.com

        sigservices:
          vars:
            service_port: 5000
            config: config-sigservice.yaml
          hosts:
            sigservice-machine1:
              config_dir: "{{top_config_dir}}/sigverifier"
              ansible_host: tokentestbed11.sl.cloud9.ibm.com

        shardsservices:
          vars:
            service_port: 5001
            config: config-shardsservice.yaml
          hosts:
            shardsservice-machine1:
              config_dir: "{{top_config_dir}}/shardsserver1"
              db_dir: "{{config_dir}}/db"
              ansible_host: tokentestbed12.sl.cloud9.ibm.com
            shardsservice-machine2:
              config_dir: "{{top_config_dir}}/shardsserver2"
              db_dir: "{{config_dir}}/db"
              ansible_host: tokentestbed13.sl.cloud9.ibm.com

        orderingservices:
          vars:
            config: orderer.yaml
            organization: DefaultOrdererOrg
            domain: example.com
#            ops_port: "{{prometheus_exporter_port}}" #TODO: Adapt template to use 0.0.0.0 before activating
          hosts:
            orderingservice-machine1:
              config_dir: "{{top_config_dir}}/orderer1"
              service_port: 7050
              cluster_port: 7070
              ansible_host: tokentestbed7.sl.cloud9.ibm.com
            orderingservice-machine2:
              config_dir: "{{top_config_dir}}/orderer2"
              service_port: 7050
              cluster_port: 7070
              ansible_host: tokentestbed8.sl.cloud9.ibm.com
            orderingservice-machine3:
              config_dir: "{{top_config_dir}}/orderer3"
              service_port: 7050
              cluster_port: 7070
              ansible_host: tokentestbed9.sl.cloud9.ibm.com
            orderingservice-machine4:
              config_dir: "{{top_config_dir}}/orderer4"
              service_port: 7051
              cluster_port: 7071
              ansible_host: tokentestbed7.sl.cloud9.ibm.com
            orderingservice-machine5:
              config_dir: "{{top_config_dir}}/orderer5"
              service_port: 7051
              cluster_port: 7071
              ansible_host: tokentestbed8.sl.cloud9.ibm.com

        peerservices:
          vars:
            config: core.yaml
            profile: profile.yaml
            organization: DefaultPeerOrg
            domain: example.com
            service_port: 7050
          hosts:
            peerservice-machine1:
              config_dir: "{{top_config_dir}}/peer0"
              ansible_host: tokentestbed4.sl.cloud9.ibm.com


        fscservices:
          vars:
            config: core.yaml
            demo_views: github.ibm.com/decentralized-trust-research/fts-sc/demo/views
            organization: DefaultPeerOrg
            domain: example.com
          hosts:
            lib-p2p-bootstrap-node:
              ansible_host: tokentestbed3.sl.cloud9.ibm.com
              service_port: 8000
              p2p_port: 8020
              config_dir: "{{top_config_dir}}/lib-p2p"
              bootstrap: true
            auditor:
              ansible_host: tokentestbed4.sl.cloud9.ibm.com
              service_port: 8001
              p2p_port: 8021
              ops_port: 8081
              web_port: 9081
              config_dir: "{{top_config_dir}}/auditor"
              auditor: true
              certifier: true
              view_factories:
                - id: initRegisterAuditor
                  factory: "{{demo_views}}/RegisterAuditorViewFactory"
                - id: initRegisterCertifier
                  factory: "{{demo_views}}/RegisterCertifierViewFactory"
                - id: historyAuditing
                  factory: "{{demo_views}}/ListAuditedTransactionsViewFactory"
            issuer:
              ansible_host: tokentestbed3.sl.cloud9.ibm.com
              service_port: 8002
              p2p_port: 8022
              ops_port: 8082
              web_port: 9082
              config_dir: "{{top_config_dir}}/issuer"
              issuer_identities:
                - default
                - id1
              owner_identities:
                - default
                - owner
              view_factories:
                - id: issue
                  factory: "{{demo_views}}/IssueCashViewFactory"

            alice:
              ansible_host: tokentestbed6.sl.cloud9.ibm.com
              service_port: 8003
              p2p_port: 8023
              ops_port: 8083
              web_port: 9083
              config_dir: "{{top_config_dir}}/alice"
              owner_identities:
                - id1
              responders:
                - responder: "{{demo_views}}/AcceptIssuedCashView"
                  initiator: "{{demo_views}}/IssueCashView"
                - responder: "{{demo_views}}/AcceptTransferCashView"
                  initiator: "{{demo_views}}/TransferView"
              view_factories:
                - id: transfer
                  factory: "{{demo_views}}/TransferViewFactory"
                - id: balance
                  factory: "{{demo_views}}/BalanceViewFactory"
                - id: registerQRCode
                  factory: "{{demo_views}}/QRCodeRegisterViewFactory"
                - id: acceptedTransactionsHistory
                  factory: "{{demo_views}}/ListAcceptedTransactionsViewFactory"
                - id: enrollmentID
                  factory: "{{demo_views}}/GetEnrollmentIDViewFactory"
                - id: txStatusByNonce
                  factory: "{{demo_views}}/TxStatusByNonceViewFactory"

            bob:
              ansible_host: tokentestbed5.sl.cloud9.ibm.com
              service_port: 8004
              p2p_port: 8024
              ops_port: 8084
              web_port: 9084
              config_dir: "{{top_config_dir}}/bob"
              owner_identities:
                - id1
              responders:
                - responder: "{{demo_views}}/AcceptIssuedCashView"
                  initiator: "{{demo_views}}/IssueCashView"
                - responder: "{{demo_views}}/AcceptTransferCashView"
                  initiator: "{{demo_views}}/TransferView"
              view_factories:
                - id: transfer
                  factory: "{{demo_views}}/TransferViewFactory"
                - id: balance
                  factory: "{{demo_views}}/BalanceViewFactory"
                - id: registerQRCode
                  factory: "{{demo_views}}/QRCodeRegisterViewFactory"
                - id: acceptedTransactionsHistory
                  factory: "{{demo_views}}/ListAcceptedTransactionsViewFactory"
                - id: enrollmentID
                  factory: "{{demo_views}}/GetEnrollmentIDViewFactory"
                - id: txStatusByNonce
                  factory: "{{demo_views}}/TxStatusByNonceViewFactory"
            endorser-1: # Only one endorser supported currently
              ansible_host: tokentestbed3.sl.cloud9.ibm.com
              service_port: 8005
              p2p_port: 8025
              config_dir: "{{top_config_dir}}/endorser1"
              endorser: true

        sidecars:
          vars:
            inherit_peer: peerservice-machine1
            config: config-sidecar.yaml
            service_port: 5050
            organization: DefaultPeerOrg
            domain: example.com
          hosts:
            sidecar-machine:
              ansible_host: tokentestbed10.sl.cloud9.ibm.com

    clients:
      children:
        sidecarclients:
          vars:
            config: config-sidecar-client.yaml
            inherit_peer: peerservice-machine1 # Used for connecting to the orderer
            inherit_endorser: endorser-1 # Used for signing the TXs for the sig verifier
          hosts:
            sidecar-client-machine1:
              profile: profile-sidecar-client.yaml
              ansible_host: tokentestbed1.sl.cloud9.ibm.com

        ordererlisteners:
          vars:
            config: config-orderer-listener.yaml
            inherit_peer: peerservice-machine1
          hosts:
            ordererlistener-machine1:
              config_dir: "{{top_config_dir}}/ordererlistener1"
              ansible_host: tokentestbed2.sl.cloud9.ibm.com

    monitoring:
      hosts:
        monitoring-machine:
          ansible_host: tokentestbed15.sl.cloud9.ibm.com
          jaeger_exporter_port: 14268