all:
  vars:
    ansible_connection: local

    # The user of the deployment machine
    ansible_user: "{{lookup('env', 'USER')}}"

    # Where to transfer the binary and config files on the deployment machines
    root_path: "{{lookup('env', 'GOPATH')}}/src/github.com/decentralized-trust-research/scalable-committer"
    binary_dir: "{{root_path + '/eval/experiments/local-bin/'}}"
    top_config_dir: "{{root_path + '/eval/experiments/local-configs/'}}"
    os: osx

  children:
    services:
      vars:
        ansible_user: root
        ansible_host: localhost
      children:

        orderingservices:
          vars:
            config: orderer.yaml
            organization: DefaultOrdererOrg
            domain: example.com #TODO: Adapt topology
          hosts:
            orderingservice-machine1:
              config_dir: "{{top_config_dir + '/orderer0'}}"
              service_port: 7050
              cluster_port: 7060
              ops_port: 8440
            orderingservice-machine2:
              config_dir: "{{top_config_dir}}/orderer1"
              service_port: 7051
              cluster_port: 7061
              ops_port: 8441

        peerservices:
          vars:
            config: core.yaml
            organization: DefaultPeerOrg
            profile: profile.yaml
            domain: example.com
          hosts:
            peerservice-machine1:
              config_dir: "{{top_config_dir}}/peer0"
              service_port: 7001

        ordererlisteners:
          vars:
            config: config-orderer-listener.yaml
            inherit_peer: peerservice-machine1
          hosts:
            ordererlistener-machine1:
              prometheus_exporter_port: 2117
              config_dir: "{{top_config_dir}}/listener0"
            ordererlistener-machine2:
              prometheus_exporter_port: 2118
              config_dir: "{{top_config_dir}}/listener1"

        orderersubmitters:
          vars:
            config: config-orderer-submitter.yaml
            inherit_peer: peerservice-machine1
          hosts:
            orderersubmitter-machine1:
              prometheus_exporter_port: 2119
              config_dir: "{{top_config_dir}}/submitter0"
            orderersubmitter-machine2:
              prometheus_exporter_port: 2120
              config_dir: "{{top_config_dir}}/submitter1"