all:
  vars:
    ansible_connection: local

    # The user of the deployment machine
    ansible_user: "{{lookup('env', 'USER')}}"

    # Where to transfer the binary and config files on the deployment machines
    root_path: "{{lookup('env', 'GOPATH')}}/src/github.com/decentralized-trust-research/scalable-committer"
    binary_dir: "{{root_path}}/eval/experiments/local-bin/"
    top_config_dir: "{{root_path}}/eval/experiments/local-configs"
    os: osx

  children:
    services:
      vars:
        ansible_host: 127.0.0.1
      children:

        coordinators:
          vars:
            config: config-coordinator.yaml
          hosts:
            coordinator-machine:
              config_dir: "{{top_config_dir}}/coordinator"
              service_port: 5002
              prometheus_exporter_port: 2112

        sigservices:
          vars:
            config: config-sigservice.yaml
          hosts:
            sigservice-machine1:
              config_dir: "{{top_config_dir}}/sigservice1"
              service_port: 5000
              prometheus_exporter_port: 2110
            sigservice-machine2:
              config_dir: "{{top_config_dir}}/sigservice2"
              service_port: 5004
              prometheus_exporter_port: 2114

        shardsservices:
          vars:
            config: config-shardsservice.yaml
          hosts:
            shardsservice-machine:
              config_dir: "{{top_config_dir}}/shardsservice"
              service_port: 5001
              prometheus_exporter_port: 2115

        orderingservices:
          vars:
            config: orderer.yaml
            organization: DefaultOrdererOrg
            domain: example.com
          hosts:
            orderingservice-machine1:
              config_dir: "{{top_config_dir}}/orderer0"
              service_port: 7050
              cluster_port: 7070
              ops_port: 8440
            orderingservice-machine2:
              config_dir: "{{top_config_dir}}/orderer1"
              service_port: 7051
              cluster_port: 7071
              ops_port: 8441
            orderingservice-machine3:
              config_dir: "{{top_config_dir}}/orderer2"
              service_port: 7052
              cluster_port: 7072
              ops_port: 8442
            orderingservice-machine4:
              config_dir: "{{top_config_dir}}/orderer3"
              service_port: 7053
              cluster_port: 7073
              ops_port: 8443

        peerservices:
          vars:
            config: core.yaml
            profile: profile.yaml
            organization: DefaultPeerOrg
            domain: example.com
          hosts:
            peerservice-machine1:
              config_dir: "{{top_config_dir}}/peer0"
              service_port: 7001

        fscservices:
          vars:
            config: core.yaml
            views: github.com/hyperledger-labs/fabric-token-sdk/integration/token/fungible/views
            organization: DefaultPeerOrg
            domain: example.com
          hosts:
            lib-p2p-bootstrap-node: # Must be first, because it's the bootstrap node (NWO particularity)
              config_dir: "{{top_config_dir}}/lib_p2p"
              service_port: 8007
              p2p_port: 8027
            issuer:
              config_dir: "{{top_config_dir}}/issuer"
              ops_port: 8080
              web_port: 9080
              service_port: 8000
              p2p_port: 8020
              view_factories:
                - id: issue
                  factory: "{{views}}/IssueCashViewFactory"
                - id: transfer
                  factory: "{{views}}/TransferViewFactory"
                - id: transferWithSelector
                  factory: "{{views}}/TransferWithSelectorViewFactory"
                - id: redeem
                  factory: "{{views}}/RedeemViewFactory"
                - id: historyIssuedToken
                  factory: "{{views}}/ListIssuedTokensViewFactory"
                - id: issuedTokenQuery
                  factory: "{{views}}/ListIssuedTokensViewFactory"
                - id: balance
                  factory: "{{views}}/BalanceViewFactory"
                - id: GetEnrollmentID
                  factory: "{{views}}/GetEnrollmentIDViewFactory"
                - id: acceptedTransactionHistory
                  factory: "{{views}}/ListAcceptedTransactionsViewFactory"
                - id: transactionInfo
                  factory: "{{views}}/TransactionInfoViewFactory"
                - id: CheckPublicParamsMatch
                  factory: "{{views}}/CheckPublicParamsMatchViewFactory"
                - id: CheckTTXDB
                  factory: "{{views}}/CheckTTXDBViewFactory"
                - id: RegisterIssuerWallet
                  factory: "{{views}}/RegisterIssuerWalletViewFactory"
                - id: PruneInvalidUnspentTokens
                  factory: "{{views}}/PruneInvalidUnspentTokensViewFactory"
                - id: WhoDeletedToken
                  factory: "{{views}}/WhoDeletedTokenViewFactory"

            alice:
              config_dir: "{{top_config_dir}}/alice"
              ops_port: 8081
              web_port: 9081
              service_port: 8001
              p2p_port: 8021
              responders:
                - responder: "{{views}}/AcceptCashView"
                  initiator: "{{views}}/IssueCashView"
                - responder: "{{views}}/AcceptCashView"
                  initiator: "{{views}}/TransferView"
                - responder: "{{views}}/AcceptCashView"
                  initiator: "{{views}}/TransferWithSelectorView"
                - responder: "{{views}}/AcceptPreparedCashView"
                  initiator: "{{views}}/PrepareTransferView"
              view_factories:
                - id: transfer
                  factory: "{{views}}/TransferViewFactory"
                - id: transferWithSelector
                  factory: "{{views}}/TransferWithSelectorViewFactory"
                - id: redeem
                  factory: "{{views}}/RedeemViewFactory"
                - id: swap
                  factory: "{{views}}/SwapInitiatorViewFactory"
                - id: history
                  factory: "{{views}}/ListUnspentTokensViewFactory"
                - id: balance
                  factory: "{{views}}/BalanceViewFactory"
                - id: GetEnrollmentID
                  factory: "{{views}}/GetEnrollmentIDViewFactory"
                - id: acceptedTransactionHistory
                  factory: "{{views}}/ListAcceptedTransactionsViewFactory"
                - id: transactionInfo
                  factory: "{{views}}/TransactionInfoViewFactory"
                - id: prepareTransfer
                  factory: "{{views}}/PrepareTransferViewFactory"
                - id: CheckPublicParamsMatch
                  factory: "{{views}}/CheckPublicParamsMatchViewFactory"
                - id: CheckTTXDB
                  factory: "{{views}}/CheckTTXDBViewFactory"
                - id: SetTransactionOwnerStatus
                  factory: "{{views}}/SetTransactionOwnerStatusViewFactory"
                - id: PruneInvalidUnspentTokens
                  factory: "{{views}}/PruneInvalidUnspentTokensViewFactory"
                - id: WhoDeletedToken
                  factory: "{{views}}/WhoDeletedTokenViewFactory"
                - id: ListVaultUnspentTokens
                  factory: "{{views}}/ListVaultUnspentTokensViewFactory"

                - id: broadcastPreparedTransfer
                  factory: "{{views}}/BroadcastPreparedTransferViewFactory"

            bob:
              config_dir: "{{top_config_dir}}/bob"
              ops_port: 8082
              web_port: 9082
              service_port: 8002
              p2p_port: 8022
              responders:
                - responder: "{{views}}/AcceptCashView"
                  initiator: "{{views}}/IssueCashView"
                - responder: "{{views}}/AcceptCashView"
                  initiator: "{{views}}/TransferView"
                - responder: "{{views}}/AcceptCashView"
                  initiator: "{{views}}/TransferWithSelectorView"
                - responder: "{{views}}/AcceptPreparedCashView"
                  initiator: "{{views}}/PrepareTransferView"

                - responder: "{{views}}/SwapResponderView"
                  initiator: "{{views}}/SwapInitiatorView"
              view_factories:
                - id: transfer
                  factory: "{{views}}/TransferViewFactory"
                - id: transferWithSelector
                  factory: "{{views}}/TransferWithSelectorViewFactory"
                - id: redeem
                  factory: "{{views}}/RedeemViewFactory"
                - id: swap
                  factory: "{{views}}/SwapInitiatorViewFactory"
                - id: history
                  factory: "{{views}}/ListUnspentTokensViewFactory"
                - id: balance
                  factory: "{{views}}/BalanceViewFactory"
                - id: GetEnrollmentID
                  factory: "{{views}}/GetEnrollmentIDViewFactory"
                - id: acceptedTransactionHistory
                  factory: "{{views}}/ListAcceptedTransactionsViewFactory"
                - id: transactionInfo
                  factory: "{{views}}/TransactionInfoViewFactory"
                - id: prepareTransfer
                  factory: "{{views}}/PrepareTransferViewFactory"
                - id: CheckPublicParamsMatch
                  factory: "{{views}}/CheckPublicParamsMatchViewFactory"
                - id: CheckTTXDB
                  factory: "{{views}}/CheckTTXDBViewFactory"
                - id: SetTransactionOwnerStatus
                  factory: "{{views}}/SetTransactionOwnerStatusViewFactory"
                - id: PruneInvalidUnspentTokens
                  factory: "{{views}}/PruneInvalidUnspentTokensViewFactory"
                - id: WhoDeletedToken
                  factory: "{{views}}/WhoDeletedTokenViewFactory"
                - id: ListVaultUnspentTokens
                  factory: "{{views}}/ListVaultUnspentTokensViewFactory"

                - id: TokenSelectorUnlock
                  factory: "{{views}}/TokenSelectorUnlockViewFactory"
                - id: FinalityWithTimeout
                  factory: "{{views}}/FinalityWithTimeoutViewFactory"
            endorser-1:
              config_dir: "{{top_config_dir}}/endorser1"
              template: endorser
              service_port: 8003
              p2p_port: 8023
            endorser-2:
              config_dir: "{{top_config_dir}}/endorser2"
              template: endorser
              service_port: 8004
              p2p_port: 8024
            endorser-3:
              config_dir: "{{top_config_dir}}/endorser3"
              template: endorser
              service_port: 8005
              p2p_port: 8025
            endorser-4:
              config_dir: "{{top_config_dir}}/endorser4"
              template: endorser
              service_port: 8006
              p2p_port: 8026

        sidecars:
          vars:
            inherit_peer: peerservice-machine1
            config: config-sidecar.yaml
          hosts:
            sidecar-machine:
              config_dir: "{{top_config_dir}}/sidecar"
              service_port: 1234
              prometheus_exporter_port: 2111

        sidecarclients:
          vars:
            config: config-sidecar-client.yaml
            inherit_peer: peerservice-machine1
          hosts:
            sidecar-client-machine1:
              profile: profile-sidecar-client.yaml
              prometheus_exporter_port: 2116
              config_dir: "{{top_config_dir}}/sidecarclient0/"
            sidecar-client-machine2:
              prometheus_exporter_port: 2117
              config_dir: "{{top_config_dir}}/sidecarclient1/"

        monitoring:
          hosts:
            monitoring-machine:
              jaeger_exporter_port: 14268