all:
  vars:
    ansible_connection: local

    # The user of the deployment machine
    ansible_user: "{{lookup('env', 'USER')}}"

    # Where to transfer the binary and config files on the deployment machines
    root_path: /Users/lio/go/src/github.com/decentralized-trust-research/scalable-committer
    binary_dir: "{{root_path + '/eval/experiments/local-bin/'}}"
    top_config_dir: "{{root_path + '/eval/experiments/local-configs'}}"
    os: osx

  children:
    services:
      children:

        blockgens:
          vars:
            config: config-blockgen.yaml
          hosts:
            blockgen-machine:
              config_dir: "{{top_config_dir}}/blockgen"
              profile: profile-blockgen.yaml
              ansible_host: localhost
              prometheus_exporter_port: 2113

        coordinators:
          vars:
            config: config-coordinator.yaml
          hosts:
            coordinator-machine:
              config_dir: "{{top_config_dir}}/coordinator"
              ansible_host: localhost
              service_port: 5002
              prometheus_exporter_port: 2112

        sigservices:
          vars:
            config: config-sigservice.yaml
          hosts:
            sigservice-machine1:
              ansible_host: localhost
              config_dir: "{{top_config_dir}}/sigservice1"
              service_port: 5000
              prometheus_exporter_port: 2110
            sigservice-machine2:
              ansible_host: localhost
              config_dir: "{{top_config_dir}}/sigservice2"
              service_port: 5004
              prometheus_exporter_port: 2114

        shardsservices:
          vars:
            config: config-shardsservice.yaml
          hosts:
            shardsservice-machine:
              ansible_host: localhost
              config_dir: "{{top_config_dir}}/shardsservice"
              db_dir: "{{config_dir}}/db"
              service_port: 5001
              prometheus_exporter_port: 2115


        monitoring:
          hosts:
            monitoring-machine:
              ansible_host: localhost
              jaeger_exporter_port: 14268