all:
  vars:
    ansible_connection: local

    # The user of the deployment machine
    ansible_user: "{{lookup('env', 'USER')}}"

    # Where to transfer the binary and config files on the deployment machines
    root_path: "{{lookup('env', 'GOPATH')}}/src/github.com/decentralized-trust-research/scalable-committer"
    top_binary_dir: "{{root_path + '/eval/experiments/local-bin/'}}"
    top_config_dir: "{{root_path + '/eval/experiments/local-configs/'}}"
    os: osx

  children:
    services:
      vars:
        ansible_user: root
        ansible_host: localhost
      children:

        orderingservices:
          vars:
            ansible_connection: ssh
            ansible_user: root
            os: linux
            config: orderer.yaml
            organization: DefaultOrdererOrg
            domain: example.com
            config_dir: /root/config
            binary_dir: /root/bin
            service_port: 7050
            cluster_port: 7070
            admin_port: 9440
            ops_port: 2112
          hosts:
            orderingservice-machine1:
              ansible_host: tokentestbed10.sl.cloud9.ibm.com
            orderingservice-machine2:
              ansible_host: tokentestbed12.sl.cloud9.ibm.com
            orderingservice-machine3:
              ansible_host: tokentestbed13.sl.cloud9.ibm.com
            orderingservice-machine4:
              ansible_host: tokentestbed14.sl.cloud9.ibm.com

        peerservices:
          vars:
            config: core.yaml
            organization: DefaultPeerOrg
            profile: profile.yaml
            domain: example.com
          hosts:
            peerservice-machine1:
              config_dir: "{{top_config_dir}}/peer0"
              binary_dir: "{{top_binary_dir}}/peer0"
              service_port: 7001

    clients:
      children:
        ordererlisteners:
          vars:
            config: config-orderer-listener.yaml
            inherit_peer: peerservice-machine1
          hosts:
            ordererlistener-machine1:
              prometheus_exporter_port: 2117
              config_dir: "{{top_config_dir}}/listener0"
              binary_dir: "{{top_binary_dir}}/listener0"
            ordererlistener-machine2:
              prometheus_exporter_port: 2118
              config_dir: "{{top_config_dir}}/listener1"
              binary_dir: "{{top_binary_dir}}/listener1"

        orderersubmitters:
          vars:
            config: config-orderer-submitter.yaml
            inherit_peer: peerservice-machine1
          hosts:
            orderersubmitter-machine1:
              prometheus_exporter_port: 2119
              config_dir: "{{top_config_dir}}/submitter0"
              binary_dir: "{{top_binary_dir}}/submitter0"
            orderersubmitter-machine2:
              prometheus_exporter_port: 2120
              config_dir: "{{top_config_dir}}/submitter1"
              binary_dir: "{{top_binary_dir}}/submitter1"