all:
  vars:
    ansible_connection: ssh
    ansible_user: "{{lookup('env', 'USER')}}"
    binary_dir: /root/bin/
    config_dir: /root/config/ # Opening the file from the app does not work if we use ~/
    os: linux
    prometheus_exporter_port: 2112

  children:
    services:
      vars:
        ansible_user: root
      children:

        coordinators:
          vars:
            service_port: 5002
            config: config-coordinator.yaml
          hosts:
            coordinator-machine:
              ansible_host: tokentestbed1.sl.cloud9.ibm.com

        sigservices:
          vars:
            service_port: 5000
            config: config-sigservice.yaml
          hosts:
            sigservice-machine1:
              ansible_host: tokentestbed2.sl.cloud9.ibm.com

        shardsservices:
          vars:
            service_port: 5001
            config: config-shardsservice.yaml
            db_dir: "{{config_dir}}/db"
          hosts:
            shardsservice-machine1:
              ansible_host: tokentestbed3.sl.cloud9.ibm.com

        orderingservices:
          vars:
            config: orderer.yaml
            organization: DefaultOrdererOrg
            domain: example.com
            service_port: 7050
            cluster_port: 7070
#            ops_port: "{{prometheus_exporter_port}}" #TODO: Adapt template to use 0.0.0.0 before activating
          hosts:
            orderingservice-machine1:
              ansible_host: tokentestbed4.sl.cloud9.ibm.com
            orderingservice-machine2:
              ansible_host: tokentestbed5.sl.cloud9.ibm.com
            orderingservice-machine3:
              ansible_host: tokentestbed6.sl.cloud9.ibm.com

        peerservices:
          vars:
            config: core.yaml
            profile: profile.yaml
            organization: DefaultPeerOrg
            domain: example.com
            service_port: 7050
          hosts:
            peerservice-machine1:
              ansible_host: tokentestbed7.sl.cloud9.ibm.com

        sidecars:
          vars:
            inherit_peer: peerservice-machine1
            config: config-sidecar.yaml
            service_port: 5050
          hosts:
            sidecar-machine:
              ansible_host: tokentestbed8.sl.cloud9.ibm.com

        sidecarclients:
          vars:
            config: config-sidecar-client.yaml
            inherit_peer: peerservice-machine1
          hosts:
            sidecar-client-machine1:
              ansible_host: tokentestbed9.sl.cloud9.ibm.com
            sidecar-client-machine2:
              profile: profile-sidecar-client.yaml
              ansible_host: tokentestbed10.sl.cloud9.ibm.com

#        monitoring:
#          hosts:
#            monitoring-machine:
#              ansible_host: tokentestbed16.sl.cloud9.ibm.com
#              jaeger_exporter_port: 14268