all:
  vars:
    ansible_connection: local

    # The user of the deployment machine
    ansible_user: "{{lookup('env', 'USER')}}"

    # Where to transfer the binary and config files on the deployment machines
    root_path: "{{lookup('env', 'GOPATH')}}/src/github.com/decentralized-trust-research/scalable-committer"
    binary_dir: "{{root_path}}/eval/experiments/local-bin/"
    top_config_dir: "{{root_path}}/eval/experiments/local-configs"
    os: osx

  children:
    services:
      vars:
        ansible_host: 127.0.0.1
      children:

        coordinators:
          vars:
            config: config-coordinator.yaml
          hosts:
            coordinator-machine:
              config_dir: "{{top_config_dir}}/coordinator"
              service_port: 5002
              prometheus_exporter_port: 2112

        sigservices:
          vars:
            config: config-sigservice.yaml
          hosts:
            sigservice-machine1:
              config_dir: "{{top_config_dir}}/sigservice1"
              service_port: 5000
              prometheus_exporter_port: 2110
            sigservice-machine2:
              config_dir: "{{top_config_dir}}/sigservice2"
              service_port: 5004
              prometheus_exporter_port: 2114

        shardsservices:
          vars:
            config: config-shardsservice.yaml
          hosts:
            shardsservice-machine:
              config_dir: "{{top_config_dir}}/shardsservice"
              db_dir: "{{config_dir}}/db"
              service_port: 5001
              prometheus_exporter_port: 2115

        orderingservices:
          vars:
            config: orderer.yaml
            organization: DefaultOrdererOrg
            domain: example.com
          hosts:
            orderingservice-machine1:
              config_dir: "{{top_config_dir}}/orderer0"
              service_port: 7050
              cluster_port: 7070
              ops_port: 8440
            orderingservice-machine2:
              config_dir: "{{top_config_dir}}/orderer1"
              service_port: 7051
              cluster_port: 7071
              ops_port: 8441
            orderingservice-machine3:
              config_dir: "{{top_config_dir}}/orderer2"
              service_port: 7052
              cluster_port: 7072
              ops_port: 8442
            orderingservice-machine4:
              config_dir: "{{top_config_dir}}/orderer3"
              service_port: 7053
              cluster_port: 7073
              ops_port: 8443

        peerservices:
          vars:
            config: core.yaml
            profile: profile.yaml
            organization: DefaultPeerOrg
            domain: example.com
          hosts:
            peerservice-machine1:
              config_dir: "{{top_config_dir}}/peer0"
              service_port: 7001

        fscservices:
          vars:
            config: core.yaml
            token_views: github.com/hyperledger-labs/fabric-token-sdk/integration/token/fungible/views
            demo_views: github.ibm.com/decentralized-trust-research/fts-sc/demo/views
            organization: DefaultPeerOrg
            domain: example.com
          hosts:
            lib-p2p-bootstrap-node: # Must be first, because it's the bootstrap node (NWO particularity)
              config_dir: "{{top_config_dir}}/lib_p2p"
              service_port: 8007
              p2p_port: 8027
              bootstrap: true
            auditor:
              config_dir: "{{top_config_dir}}/auditor"
              ops_port: 8088
              web_port: 9088
              service_port: 8008
              p2p_port: 8028
              auditor: true
              certifier: true
              view_factories:
                - id: registerAuditor
                  factory: "{{token_views}}/RegisterAuditorViewFactory"
                - id: registerCertifier
                  factory: "{{token_views}}/RegisterCertifierViewFactory"
            issuer:
              config_dir: "{{top_config_dir}}/issuer"
              ops_port: 8080
              web_port: 9080
              service_port: 8000
              p2p_port: 8020
              issuer_identities:
                - default
                - id1
              owner_identities:
                - default
                - owner
              view_factories:
                - id: issue
                  factory: "{{token_views}}/IssueCashViewFactory"

            alice:
              config_dir: "{{top_config_dir}}/alice"
              ops_port: 8081
              web_port: 9081
              service_port: 8001
              p2p_port: 8021
              owner_identities:
                - id1
              responders:
                - responder: "{{demo_views}}/AcceptIssuedCashView"
                  initiator: "{{token_views}}/IssueCashView"
                - responder: "{{demo_views}}/AcceptTransferCashView"
                  initiator: "{{token_views}}/TransferView"
              view_factories:
                - id: transfer
                  factory: "{{token_views}}/TransferViewFactory"
                - id: balance
                  factory: "{{token_views}}/BalanceViewFactory"
                - id: registerQRCode
                  factory: "{{demo_views}}/QRCodeRegisterViewFactory"
                - id: acceptedTransactionsHistory
                  factory: "{{token_views}}/ListAcceptedTransactionsViewFactory"
                - id: enrollmentID
                  factory: "{{token_views}}/GetEnrollmentIDViewFactory"

            bob:
              config_dir: "{{top_config_dir}}/bob"
              ops_port: 8082
              web_port: 9082
              service_port: 8002
              p2p_port: 8022
              owner_identities:
                - id1
              responders:
                - responder: "{{demo_views}}/AcceptIssuedCashView"
                  initiator: "{{token_views}}/IssueCashView"
                - responder: "{{demo_views}}/AcceptTransferCashView"
                  initiator: "{{token_views}}/TransferView"
              view_factories:
                - id: transfer
                  factory: "{{token_views}}/TransferViewFactory"
                - id: balance
                  factory: "{{token_views}}/BalanceViewFactory"
                - id: registerQRCode
                  factory: "{{demo_views}}/QRCodeRegisterViewFactory"
                - id: acceptedTransactionsHistory
                  factory: "{{token_views}}/ListAcceptedTransactionsViewFactory"
                - id: enrollmentID
                  factory: "{{token_views}}/GetEnrollmentIDViewFactory"
            endorser-1:
              config_dir: "{{top_config_dir}}/endorser1"
              endorser: true
              service_port: 8003
              p2p_port: 8023
            endorser-2:
              config_dir: "{{top_config_dir}}/endorser2"
              endorser: true
              service_port: 8004
              p2p_port: 8024

        sidecars:
          vars:
            inherit_peer: peerservice-machine1
            config: config-sidecar.yaml
          hosts:
            sidecar-machine:
              config_dir: "{{top_config_dir}}/sidecar"
              service_port: 1234
              prometheus_exporter_port: 2111

        sidecarclients:
          vars:
            config: config-sidecar-client.yaml
            inherit_peer: peerservice-machine1
          hosts:
            sidecar-client-machine1:
              profile: profile-sidecar-client.yaml
              prometheus_exporter_port: 2116
              config_dir: "{{top_config_dir}}/sidecarclient0/"
            sidecar-client-machine2:
              prometheus_exporter_port: 2117
              config_dir: "{{top_config_dir}}/sidecarclient1/"

        orderersubmitters:
          vars:
            config: config-orderer-submitter.yaml
            inherit_peer: peerservice-machine1
          hosts:
            orderersubmitter-machine1:
              prometheus_exporter_port: 2119
              config_dir: "{{top_config_dir}}/submitter0"

        monitoring:
          hosts:
            monitoring-machine:
              jaeger_exporter_port: 14268