all:
  vars:
    ansible_connection: ssh
    ansible_user: "{{lookup('env', 'USER')}}"
    binary_dir: /root/bin/
    config_dir: /root/config/ # Opening the file from the app does not work if we use ~/
    creds_dir: "{{config_dir}}"
    os: linux
    prometheus_exporter_port: 2112
    skip_prefix_when_copy: ['orderer.yaml']

  children:
    services:
      vars:
        ansible_user: "root"
      children:
        orderingservices:
          vars:
            config: orderer.yaml
            genesis_dir: "{{config_dir}}"
            ledger_dir: "{{config_dir + '/ledger'}}"
            service_port: 7050
            ops_port: 8440
            admin_port: 9440
          hosts:
            orderingservice-machine1:
              orderer_name: orderer_0
              ansible_host: "tokentestbed4.sl.cloud9.ibm.com"
            orderingservice-machine2:
              orderer_name: orderer_1
              ansible_host: "tokentestbed5.sl.cloud9.ibm.com"
            orderingservice-machine3:
              orderer_name: orderer_2
              ansible_host: "tokentestbed6.sl.cloud9.ibm.com"

        ordererlisteners:
          hosts:
            ordererlistener-machine1:
              ansible_host: "tokentestbed7.sl.cloud9.ibm.com"
            ordererlistener-machine2:
              ansible_host: "tokentestbed8.sl.cloud9.ibm.com"


        orderersubmitters:
          hosts:
            orderersubmitter-machine1:
              ansible_host: "tokentestbed9.sl.cloud9.ibm.com"
            orderersubmitter-machine2:
              ansible_host: "tokentestbed10.sl.cloud9.ibm.com"