all:
  vars:
    ansible_connection: ssh
    ansible_user: "{{lookup('env', 'USER')}}"
    binary_dir: /root/bin/
    config_dir: /root/config/ # Opening the file from the app does not work if we use ~/
    creds_dir: "{{config_dir}}"
    os: linux
    prometheus_exporter_port: 2112
    skip_prefix_when_copy: ['orderer.yaml']

  children:
    services:
      vars:
        ansible_user: "root"
      children:
        orderingservices:
          vars:
            config: orderer.yaml
            genesis_dir: "{{config_dir}}"
            ledger_dir: "{{config_dir + '/ledger'}}"
            service_port: 7050
            ops_port: 8440
            admin_port: 9440
          hosts:
            orderingservice-machine1:
              orderer_name: orderer_1
              ansible_host: "tokentestbed1.sl.cloud9.ibm.com"
            orderingservice-machine2:
              orderer_name: orderer_2
              ansible_host: "tokentestbed2.sl.cloud9.ibm.com"
            orderingservice-machine3:
              orderer_name: orderer_3
              ansible_host: "tokentestbed3.sl.cloud9.ibm.com"
            orderingservice-machine4:
              orderer_name: orderer_4
              ansible_host: "tokentestbed4.sl.cloud9.ibm.com"
            orderingservice-machine5:
              orderer_name: orderer_5
              ansible_host: "tokentestbed5.sl.cloud9.ibm.com"
            orderingservice-machine6:
              orderer_name: orderer_6
              ansible_host: "tokentestbed6.sl.cloud9.ibm.com"
            orderingservice-machine7:
              orderer_name: orderer_7
              ansible_host: "tokentestbed7.sl.cloud9.ibm.com"
            orderingservice-machine8:
              orderer_name: orderer_8
              ansible_host: "tokentestbed8.sl.cloud9.ibm.com"
            orderingservice-machine9:
              orderer_name: orderer_9
              ansible_host: "tokentestbed9.sl.cloud9.ibm.com"
            orderingservice-machine10:
              orderer_name: orderer_10
              ansible_host: "tokentestbed10.sl.cloud9.ibm.com"
            orderingservice-machine11:
              orderer_name: orderer_11
              ansible_host: "tokentestbed11.sl.cloud9.ibm.com"

        ordererlisteners:
          hosts:
            ordererlistener-machine1:
              ansible_host: "tokentestbed12.sl.cloud9.ibm.com"


        orderersubmitters:
          hosts:
            orderersubmitter-machine1:
              ansible_host: "tokentestbed13.sl.cloud9.ibm.com"