all:
  vars:
    ansible_connection: ssh
    ansible_user: "{{lookup('env', 'USER')}}"
    binary_dir: /root/bin/
    config_dir: /root/config/
    os: linux
    prometheus_exporter_port: 2112

  children:
    services:
      vars:
        ansible_user: root
      children:
        orderingservices:
          vars:
            config: orderer.yaml
            organization: DefaultOrdererOrg
            domain: example.com
            service_port: 7050
            cluster_port: 7051
            ops_port: "{{prometheus_exporter_port}}"
          hosts:
            orderingservice-machine1:
              ansible_host: tokentestbed1.sl.cloud9.ibm.com
            orderingservice-machine2:
              ansible_host: tokentestbed2.sl.cloud9.ibm.com
            orderingservice-machine3:
              ansible_host: tokentestbed3.sl.cloud9.ibm.com
            orderingservice-machine4:
              ansible_host: tokentestbed4.sl.cloud9.ibm.com
            orderingservice-machine5:
              ansible_host: tokentestbed5.sl.cloud9.ibm.com

        peerservices:
          vars:
            service_port: 7000
            config: core.yaml
            organization: DefaultPeerOrg
            profile: profile.yaml
            domain: example.com
          hosts:
            peerservice-machine1:
              ansible_host: tokentestbed12.sl.cloud9.ibm.com

        ordererlisteners:
          vars:
            config: config-orderer-listener.yaml
            inherit_peer: peerservice-machine1
          hosts:
            ordererlistener-machine1:
              ansible_host: tokentestbed13.sl.cloud9.ibm.com


        orderersubmitters:
          vars:
            config: config-orderer-submitter.yaml
            inherit_peer: peerservice-machine1
          hosts:
            orderersubmitter-machine1:
              ansible_host: tokentestbed13.sl.cloud9.ibm.com