all:
  vars:
    ansible_connection: local

    # The user of the deployment machine
    ansible_user: "{{lookup('env', 'USER')}}"

    # Where to transfer the binary and config files on the deployment machines
    root_path: /Users/lio/go/src/github.com/decentralized-trust-research/scalable-committer
    binary_dir: "{{root_path + '/eval/experiments/local-bin/'}}"
    config_dir: "{{root_path + '/eval/experiments/local-configs/'}}"
    os: osx

  children:
    services:
      children:
        blockgens:
          hosts:
            blockgen-machine:
              config: config-blockgen.yaml
              block_profile: profile-blockgen.yaml
              ansible_host: "localhost"
              prometheus_exporter_port: 2113

        coordinators:
          hosts:
            coordinator-machine:
              config: config-coordinator.yaml
              ansible_host: "localhost"
              service_port: 5002
              prometheus_exporter_port: 2112

        sigservices:
          vars:
            config: config-sigservice.yaml
          hosts:
            sigservice-machine1:
              ansible_host: "localhost"
              service_port: 5000
              prometheus_exporter_port: 2110
            sigservice-machine2:
              ansible_host: "localhost"
              service_port: 5004
              prometheus_exporter_port: 2114

        shardsservices:
          vars:
            config: config-shardsservice.yaml
          hosts:
            shardsservice-machine:
              ansible_host: "localhost"
              service_port: 5001
              prometheus_exporter_port: 2115

        orderingservices:
          hosts:
            orderingservice-machine1:
              ansible_host: orderer__0
              service_port: 7050
              ops_port: 8440
              admin_port: 9440
            orderingservice-machine2:
              ansible_host: orderer__1
              service_port: 7051
              ops_port: 8441
              admin_port: 9441
            orderingservice-machine3:
              ansible_host: orderer__2
              service_port: 7052
              ops_port: 8442
              admin_port: 9442
            orderingservice-machine4:
              ansible_host: orderer__3
              service_port: 7053
              ops_port: 8443
              admin_port: 9443

        sidecars:
          hosts:
            sidecar-machine:
              config: config-sidecar.yaml
              ansible_host: "localhost"
              service_port: 1234
              prometheus_exporter_port: 2111

        sidecarclients:
          vars:
            config: config-sidecar-client.yaml
          hosts:
            sidecar-client-machine1:
              block_profile: profile-blockgen.yaml
              ansible_host: "localhost"
              prometheus_exporter_port: 2116
            sidecar-client-machine2:
              ansible_host: "localhost"
              prometheus_exporter_port: 2117

        monitoring:
          hosts:
            monitoring-machine:
              ansible_host: "localhost"
              jaeger_exporter_port: 14268