all:
  vars:
    ansible_connection: ssh
    ansible_user: "{{lookup('env', 'USER')}}"
    binary_dir: /root/bin/
    top_config_dir: /root/config
    config_dir: "{{top_config_dir}}"
    os: linux
    prometheus_exporter_port: 2112

  children:
    services:
      vars:
        ansible_user: root
      children:

        coordinators:
          vars:
            service_port: 5002
            config: config-coordinator.yaml
          hosts:
            coordinator-machine:
              ansible_host: tokentestbed5.sl.cloud9.ibm.com

        sigservices:
          vars:
            service_port: 5000
            config: config-sigservice.yaml
          hosts:
            sigservice-machine:
              ansible_host: tokentestbed6.sl.cloud9.ibm.com

        shardsservices:
          vars:
            service_port: 5001
            config: config-shardsservice.yaml
            db_dir: "{{config_dir}}/db"
          hosts:
            shardsservice-machine1:
              ansible_host: tokentestbed7.sl.cloud9.ibm.com
            shardsservice-machine2:
              ansible_host: tokentestbed8.sl.cloud9.ibm.com
            shardsservice-machine3:
              ansible_host: tokentestbed9.sl.cloud9.ibm.com

  clients:
    children:
      blockgens:
        vars:
          config: config-blockgen.yaml
        hosts:
          blockgen-machine:
            profile: profile-blockgen.yaml
            ansible_host: tokentestbed10.sl.cloud9.ibm.com

    monitoring:
      hosts:
        monitoring-machine:
          ansible_host: tokentestbed15.sl.cloud9.ibm.com
          jaeger_exporter_port: 14268