all:
  vars:
    ansible_connection: local

    # The user of the deployment machine
    ansible_user: "{{lookup('env', 'USER')}}"

    # Where to transfer the binary and config files on the deployment machines
    root_path: "{{lookup('env', 'GOPATH')}}/src/github.com/decentralized-trust-research/scalable-committer"
    top_binary_dir: "{{root_path}}/eval/experiments/local-bin/"
    top_config_dir: "{{root_path}}/eval/experiments/local-configs"
    ansible_host: 127.0.0.1
    os: osx

  children:
    services:
      children:

        coordinators:
          vars:
            config: config-coordinator.yaml
          hosts:
            coordinator-machine:
              inherit_endorser: endorser-1 # Used for setting the sig verification key
              config_dir: "{{top_config_dir}}/coordinator"
              binary_dir: "{{top_binary_dir}}/coordinator"
              service_port: 5002
              prometheus_exporter_port: 2112

        sigservices:
          vars:
            config: config-sigservice.yaml
          hosts:
            sigservice-machine1:
              config_dir: "{{top_config_dir}}/sigservice1"
              binary_dir: "{{top_binary_dir}}/sigservice1"
              service_port: 5000
              prometheus_exporter_port: 2110

        shardsservices:
          vars:
            config: config-shardsservice.yaml
          hosts:
            shardsservice-machine:
              config_dir: "{{top_config_dir}}/shardsservice"
              binary_dir: "{{top_binary_dir}}/shardsservice"
              db_dir: "{{config_dir}}/db"
              service_port: 5001
              prometheus_exporter_port: 2115

        orderingservices:
          vars:
            ansible_connection: ssh
            ansible_user: root
            os: linux
            config: orderer.yaml
            organization: DefaultOrdererOrg
            domain: example.com
            config_dir: /root/config
            binary_dir: /root/bin
            service_port: 7050
            cluster_port: 7070
            admin_port: 9440
            ops_port: 2112
          hosts:
            orderingservice-machine1:
              ansible_host: tokentestbed10.sl.cloud9.ibm.com
            orderingservice-machine2:
              ansible_host: tokentestbed12.sl.cloud9.ibm.com
            orderingservice-machine3:
              ansible_host: tokentestbed13.sl.cloud9.ibm.com
            orderingservice-machine4:
              ansible_host: tokentestbed14.sl.cloud9.ibm.com

        peerservices:
          vars:
            config: core.yaml
            profile: profile.yaml
            organization: DefaultPeerOrg
            domain: example.com
          hosts:
            peerservice-machine1:
              config_dir: "{{top_config_dir}}/peer0"
              binary_dir: "{{top_binary_dir}}/peer0"
              service_port: 7001

        fscservices:
          vars:
            config: core.yaml
            demo_views: github.ibm.com/decentralized-trust-research/fts-sc/demo/views
            organization: DefaultPeerOrg
            domain: example.com
            binary_dir: "{{top_binary_dir}}/fscnodes"
          hosts:
            lib-p2p-bootstrap-node:
              config_dir: "{{top_config_dir}}/lib_p2p"
              service_port: 8007
              p2p_port: 8027
              bootstrap: true
            dw:
              config_dir: "{{top_config_dir}}/dw"
              ops_port: 8088
              web_port: 9088
              service_port: 8008
              p2p_port: 8028
              auditor: true
              certifier: true
              view_factories:
                - id: initRegisterAuditor
                  factory: "{{demo_views}}/RegisterAuditorViewFactory"
                - id: initRegisterCertifier
                  factory: "{{demo_views}}/RegisterCertifierViewFactory"
                - id: historyAuditing
                  factory: "{{demo_views}}/ListAuditedTransactionsViewFactory"
            issuer:
              config_dir: "{{top_config_dir}}/issuer"
              ops_port: 8080
              web_port: 9080
              service_port: 8000
              p2p_port: 8020
              issuer_identities:
                - default
              owner_identities:
                - default
              view_factories:
                - id: issue
                  factory: "{{demo_views}}/IssueCashViewFactory"
              responders:
                - responder: "{{demo_views}}/WithdrawalResponderView"
                  initiator: "{{demo_views}}/WithdrawalInitiatorView"

            banka:
              config_dir: "{{top_config_dir}}/banka"
              ops_port: 8081
              web_port: 9081
              service_port: 8001
              p2p_port: 8021
              intermediary_identity: bankA
              owner_identities:
                - alice
                - charlie
              responders:
                - responder: "{{demo_views}}/AcceptIssuedCashView"
                  initiator: "{{demo_views}}/IssueCashView"
                - responder: "{{demo_views}}/AcceptTransferCashView"
                  initiator: "{{demo_views}}/TransferView"
              view_factories:
                - id: transfer
                  factory: "{{demo_views}}/TransferViewFactory"
                - id: balance
                  factory: "{{demo_views}}/BalanceViewFactory"
                - id: registerQRCode
                  factory: "{{demo_views}}/QRCodeRegisterViewFactory"
                - id: acceptedTransactionsHistory
                  factory: "{{demo_views}}/ListAcceptedTransactionsViewFactory"
                - id: enrollmentID
                  factory: "{{demo_views}}/GetEnrollmentIDViewFactory"
                - id: txStatusByNonce
                  factory: "{{demo_views}}/TxStatusByNonceViewFactory"
                - id: withdrawal
                  factory: "{{demo_views}}/WithdrawalInitiatorViewFactory"
                - id: ListOwnerWalletIDsView
                  factory: "{{demo_views}}/ListOwnerWalletIDsViewFactory"
                - id: withdrawal
                  factory: "{{demo_views}}/WithdrawalInitiatorViewFactory"

            bankb:
              config_dir: "{{top_config_dir}}/bankb"
              ops_port: 8082
              web_port: 9082
              service_port: 8002
              p2p_port: 8022
              intermediary_identity: bankB
              owner_identities:
                - bob
                - dave
              responders:
                - responder: "{{demo_views}}/AcceptIssuedCashView"
                  initiator: "{{demo_views}}/IssueCashView"
                - responder: "{{demo_views}}/AcceptTransferCashView"
                  initiator: "{{demo_views}}/TransferView"
              view_factories:
                - id: transfer
                  factory: "{{demo_views}}/TransferViewFactory"
                - id: balance
                  factory: "{{demo_views}}/BalanceViewFactory"
                - id: registerQRCode
                  factory: "{{demo_views}}/QRCodeRegisterViewFactory"
                - id: acceptedTransactionsHistory
                  factory: "{{demo_views}}/ListAcceptedTransactionsViewFactory"
                - id: enrollmentID
                  factory: "{{demo_views}}/GetEnrollmentIDViewFactory"
                - id: txStatusByNonce
                  factory: "{{demo_views}}/TxStatusByNonceViewFactory"
                - id: withdrawal
                  factory: "{{demo_views}}/WithdrawalInitiatorViewFactory"
                - id: ListOwnerWalletIDsView
                  factory: "{{demo_views}}/ListOwnerWalletIDsViewFactory"
                - id: withdrawal
                  factory: "{{demo_views}}/WithdrawalInitiatorViewFactory"

            endorser-1: # Only one endorser supported currently
              config_dir: "{{top_config_dir}}/endorser1"
              endorser: true
              ops_port: 8083
              service_port: 8003
              p2p_port: 8023
              view_factories:
                - id: listValidatedRequests
                  factory: "{{demo_views}}/ListValidatedRequestsViewFactory"

        sidecars:
          vars:
            inherit_peer: peerservice-machine1
            config: config-sidecar.yaml
            organization: DefaultPeerOrg
            domain: example.com
          hosts:
            sidecar-machine:
              config_dir: "{{top_config_dir}}/sidecar"
              binary_dir: "{{top_binary_dir}}/sidecar"
              service_port: 1234
              prometheus_exporter_port: 2111

    clients:
      children:
        sidecarclients:
          vars:
            config: config-sidecar-client.yaml
            inherit_peer: peerservice-machine1 # Used for connecting to the orderer
            inherit_endorser: endorser-1 # Used for signing the TXs for the sig verifier
          hosts:
            sidecar-client-machine1:
              profile: profile-sidecar-client.yaml
              prometheus_exporter_port: 2116
              config_dir: "{{top_config_dir}}/sidecarclient0/"
              binary_dir: "{{top_binary_dir}}/sidecarclient0"
              limiter_port: 6997
            sidecar-client-machine2:
              prometheus_exporter_port: 2117
              config_dir: "{{top_config_dir}}/sidecarclient1/"
              binary_dir: "{{top_binary_dir}}/sidecarclient1"
              limiter_port: 6998

    monitoring:
      hosts:
        monitoring-machine:
          jaeger_exporter_port: 14268
          jaeger_optl_exporter_port: 4318