coordinator-service:
  server:
    endpoint: {{.ServerEndpoint}}
  sign-verifier:
    server: 
      {{- range .SigVerifierEndpoints }}
      - endpoint: {{ . }}
      {{- end }}
  validator-committer:
    server: 
      {{- range .VCServiceEndpoints }}
      - endpoint: {{ . }}
      {{- end }}
  dependency-graph:
    num-of-local-dep-constructors: 20
    waiting-txs-limit: 10000
    num-of-workers-for-global-dep-manager: 20
    # Add monitoring configuration here if applicable
  per-channel-buffer-size-per-goroutine: 300

  monitoring:
    metrics:
      enable: true
      endpoint: {{.MetricsEndpoint}}

# For debugging, change the output to: xxx.log and the level to: DEBUG
logging:
  development: true
  enabled: true
  level: INFO
  output: