sidecar:
  server:
    endpoint: {{ .ServerEndpoint }}
    keep-alive:
      params:
        time: 300s
        timeout: 600s
      enforcement-policy:
        min-time: 60s
        permit-without-stream: false

  orderer:
    endpoint: {{ .OrdererEndpoint }}
    channel-id: {{ .ChannelID }}
    reconnect: 10s
  committer:
    endpoint: {{ .CoordinatorEndpoint }}

  ledger:
    path: {{ .LedgerPath }}

  monitoring:
    metrics:
      enable: true
      endpoint: {{ .MetricsEndpoint }}
    latency:
      span-exporter: jaeger
      sampler:
        type: blocktx
        ratio: 10
        sample-size: 100
        sample-period: 100000
      endpoint: {{ .LatencyEndpoint }}
      max-latency: 5s
      bucket-count: 1000

logging:
  development: true
  enabled: true
  level: INFO
