OrdererOrgs:
  - Name: orderer
    Domain: orderer.org
    EnableNodeOUs: true
    Specs:
      - Hostname: raft0
        SANS:
          - localhost
      - Hostname: raft1
        SANS:
            - localhost
      - Hostname: raft2
        SANS:
          - localhost

PeerOrgs:
  - Name: Org1
    Domain: org1.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
    Users:
      Count: 1
