blockgen:
  endpoint: localhost:5002
  generator:
    profile: config/local/profile-blockgen.yaml
  prometheus:
    endpoint: :2113
    latency-endpoint: localhost:14268
  server:
    endpoint: :0
logging:
  development: true
  enabled: true
  level: INFO
  output: log.txt
