coordinator:
  limits:
    dependency-graph-update-timeout: 1ms
    invalid-sig-batch-cutoff-size: 1000
    max-dependency-graph-size: 1000000
    shard-request-cut-timeout: 1ms
  prometheus:
    endpoint: :2112
    latency-endpoint: localhost:14268
  server:
    endpoint: :5002
  shards-servers:
    delete-existing-shards: true
    prefix-size-for-shard-calculation: 2
    servers:
    - endpoint: localhost:5001
      num-shards: 1
  sig-verifiers:
    endpoints:
    - localhost:5000
logging:
  development: true
  enabled: true
  level: INFO
  output: log.txt
