logging:
  development: true
  enabled: true
  level: INFO
sig-verification:
  parallel-executor:
    batch-size-cutoff: 50
    batch-time-cutoff: 10ms
    channel-buffer-size: 50
    parallelism: 40
  prometheus:
    endpoint: :2110
    latency-endpoint: localhost:14268
  scheme: Ecdsa
  server:
    endpoint: :5000
