query-service:
  # Configuration for the server
  server:
    # The server's endpoint configuration
    endpoint:
      host: localhost   # The host of the server
      port: 7003        # The port of the server
    # Credentials for the server
  database:
    endpoints:
      - localhost:5433
    username: "yugabyte"                       # The username for the database
    # TODO: pass password via environment variable
    password: "yugabyte"                       # The password for the database
    database: "yugabyte"                       # The database name
    max-connections: 10                        # The maximum size of the connection pool
    min-connections: 5                         # The minimum size of the connection pool.
  monitoring:
    server:
      endpoint: localhost:7004
  # Resource limit configurations
  min-batch-keys: 1024             # A batch will execute once it accumulated this number of keys.
  max-batch-wait: 100ms            # A batch will execute once it waited this much time.
  view-aggregation-window: 100ms   # A new view will be created if the previous view was created before this much time.
  max-aggregated-views: 1024       # A new view will be created if the previous view aggregated this number of views.
  max-view-timeout: 10s            # A view will be closed if it was opened for longer than this time.
logging:
  development: true
  enabled: true
  level: INFO
