sig-verification:
  parallel-executor:
    batch-size-cutoff: 50
    batch-time-cutoff: 10ms
    channel-buffer-size: 50
    parallelism: 40
  scheme: Ecdsa
  server:
    endpoint: localhost:5000

  monitoring:
    server:
      endpoint: localhost:2110

logging:
  development: true
  enabled: true
  level: INFO
