sig-verification:
  server:
    endpoint: :5000                                           # Overridden by ansible
  monitoring:
    metrics:
      endpoint: :2112                                         # Overridden by ansible
    latency:
      span-exporter: jaeger
      sampler:
        type: blocktx
        ratio: 10
        sample-size: 100
        sample-period: 100000
      endpoint: tokentestbed15.sl.cloud9.ibm.com:14268        # Overridden by ansible
      max-latency: 5s
      bucket-count: 1000
  scheme: "Ecdsa"
  parallel-executor:
    parallelism: 40
    # Whenever we receive a batch, we start validating the TXs independently in parallel.
    # The verification results are not grouped based on their initial block, but they return immediately after they are calculated.
    # To avoid the overhead of sending each TX separately, we group them in batches.
    # If we don't have enough responses to create a batch for a period of (batch-time-cutoff), then we emit a batch with all results waiting to be included into the next batch.
    batch-time-cutoff: 10ms
    batch-size-cutoff: 50
    channel-buffer-size: 50

logging:
  enabled: true
  level: INFO
  development: true
