coordinator:
  endpoint: :5002
  prometheus:
    endpoint: :2115
    latency-endpoint: :14268
  sig-verifiers:
    endpoints:
      - :5000
  shards-servers:
    servers:
      - endpoint: :5001
        num-shards: 1