shards-service:
  endpoint: :5001
  prometheus:
    enabled: true
    latency-enabled: true
    endpoint: :2112
  database:
    type: "rocksdb"
    root-dir: "./"
  limits:
    max-goroutines: 100
    max-shard-instances-buffer-size: 1000000
    max-pending-commits-buffer-size: 1000000
    max-phase-one-processing-workers: 50
    max-phase-two-processing-workers: 50
    max-phase-one-response-batch-item-count: 50
    phase-one-response-cut-timeout: 50ms

logging:
  enabled: true
  level: INFO
  development: true
