blockgen:
  endpoint: tokentestbed2.sl.cloud9.ibm.com:5002
  prometheus:
    endpoint: :2112
    latency-endpoint: tokentestbed15.sl.cloud9.ibm.com:14268
  generator:
    profile: ./profile-blockgen.yaml
#    limits:
#      parallelism: 3
#      channel-buffer-size: 10

logging:
  enabled: true
  level: INFO
  development: true
  output: log.txt