sidecar:
  endpoint: :5000                                               # Overridden by ansible
  prometheus:                                                   # Overridden by ansible
    endpoint: :2112
    latency-endpoint: tokentestbed15.sl.cloud9.ibm.com:14268
  orderer:
    endpoint: :7050                                             # Overridden by ansible
    channel-id: mychannel                                       # Overridden by ansible
    config-path: /root/sc/orderer                               # Overridden by ansible
    creds-path: /root/sc/orderer                                # Overridden by ansible
    msp-dir: /msp
    msp-id: Org1
    reconnect: 10s
  committer:
    endpoint: :5002                                             # Overridden by ansible
    output-channel-capacity: 20

logging:
  enabled: true
  level: INFO
  development: true
