shards-service:
  server:
    endpoint: :5001
  database:
    root-dir: ./
    type: goleveldb
  limits:
    max-pending-commits-buffer-size: 1000000
    max-phase-one-processing-workers: 50
    max-phase-one-response-batch-item-count: 50
    max-phase-two-processing-workers: 50
    max-shard-instances-buffer-size: 1000000
    phase-one-response-cut-timeout: 50ms

  monitoring:
    metrics:
      endpoint: :2111
    latency:
      span-exporter: jaeger
      sampler:
        type: blocktx
        ratio: 10
        sample-size: 100
        sample-period: 100000
      endpoint: localhost:14268
      max-latency: 5s
      bucket-count: 1000

logging:
  development: true
  enabled: true
  level: INFO
