coordinator:
  server:
    endpoint: :5002
  limits:
    dependency-graph-update-timeout: 1ms
    invalid-sig-batch-cutoff-size: 1000
    max-dependency-graph-size: 1000000
    shard-request-cut-timeout: 1ms
  shards-servers:
    delete-existing-shards: true
    prefix-size-for-shard-calculation: 2
    servers:
    - endpoint: localhost:5001
      num-shards: 1
  sig-verifiers:
    endpoints:
    - localhost:5000

  monitoring:
    metrics:
      endpoint: :2112
    latency:
      span-exporter: jaeger
      sampler:
        type: blocktx
        ratio: 10
        sample-size: 100
        sample-period: 100000
      endpoint: localhost:14268
      max-latency: 5s
      bucket-count: 1000

logging:
  development: true
  enabled: true
  level: INFO
