coordinator-client:
  endpoint: localhost:9001

monitoring:
  metrics:
    enable: true
    endpoint: :2112
  latency:
    sampler:
      type: timer
      sampling-interval: 10s
rate-limit:
  initial-limit: 1000
load-profile:
  block:
    size: 500
    buffer-size: 1000

  transaction:
    key-size: 32
    read-write-count:
      type: constant
      const: 2
    buffer-size: 500
    signature:
      scheme: ECDSA

  conflicts:
    invalid-signatures: 0.1

  tx-gen-workers: 5
  tx-sign-workers: 3
  tx-dependencies-workers: 2

  seed: 12345
