name: cbdc-tx
description: read write with nil value and nil version

block:
  size: 500
  buffer-size: 1000

transaction:
  key-size: 32
  read-write-count:
    type: constant
    const: 2
  buffer-size: 500
  signature:
    scheme: ECDSA

conflicts:
  invalid-signatures:
    # probability: 0

tx-gen-workers: 5
tx-sign-workers: 3
tx-dependencies-workers: 2

blockgen:
  # when testing coordinator performance, set only the coordinator endpoint.
  # vcservice-endpoints are not needed while testing the coordinator endpoint.
  # The block will be submitted directly to the coordinator which will distribute
  # to vcserice.
  coordinator-endpoint: "localhost:9001"
  # when testing vcservice performance as a standalone component, set only vcservice-endpoints.
  # No need to set coordinator-endpoint while testing the performance of vcservice alone.
  vcservice-endpoints:
    - "localhost:9002"
  monitoring:
    metrics:
      enable: true
      endpoint: :2112
