coordinator:
  endpoint: :5002
  prometheus:
    enabled: true
    latency-enabled: true
    endpoint: :2112
  sig-verifiers:
    endpoints:
      - tokentestbed3.sl.cloud9.ibm.com:5000
      - tokentestbed4.sl.cloud9.ibm.com:5000
      - tokentestbed5.sl.cloud9.ibm.com:5000
  shards-servers:
    servers:
      - endpoint: tokentestbed6.sl.cloud9.ibm.com:5001
        num-shards: 1
      - endpoint: tokentestbed7.sl.cloud9.ibm.com:5001
        num-shards: 1
      - endpoint: tokentestbed8.sl.cloud9.ibm.com:5001
        num-shards: 1
    delete-existing-shards: true

logging:
  enabled: true
  level: INFO
  development: true