orderer-listener:               # Overridden by ansible
  orderer: :7050
  channel-id: mychannel
  monitoring:
    metrics:
      endpoint: :2112                                         # Overridden by ansible
  orderer-connection-profile: ./orderer-connection-profile.yaml

logging:
  enabled: true
  level: INFO
  development: true
  output: log.txt