coordinator-service:
  server:
    endpoint:
      host: "localhost"
      port: 9001
  sign-verifier:
    server:
      - # server 1 configuration
        endpoint:
          host: "localhost" # The host of the server
          port: 4001        # The port of the server
      - # server 2 configuration
        endpoint:
          host: "localhost" # The host of the server
          port: 4002        # The port of the server
  validator-committer:
    server:
      - # server 1 configuration
        endpoint:
          host: "localhost" # The host of the server
          port: 5001        # The port of the server
      - # server 2 configuration
        endpoint:
          host: "localhost" # The host of the server
          port: 5002        # The port of the server
  dependency-graph:
    num-of-local-dep-constructors: 20
    waiting-txs-limit: 10000
    num-of-workers-for-global-dep-manager: 20
    # Add monitoring configuration here if applicable
  per-channel-buffer-size-per-goroutine: 300

  monitoring:
    metrics:
      enable: true
      endpoint: :2110

logging:
  development: true
  enabled: true
  level: INFO
