sidecar-client:
  prometheus:                                 # Overridden by ansible
    endpoint: :2113

  sidecar: :1234                              # Overridden by ansible
  committer: :5002                            # Overridden by ansible
  orderers:                                   # Overridden by ansible
    - :7050
    - :7051
    - :7052
  channel-id: mychannel                       # Overridden by ansible
  profile: ../../config/profile-sidecar-client.yaml # Overridden by ansible
  input-channel-capacity: 20
  parallelism: 20
  signed-envelopes: true                      # Overriden by ansible
logging:
  enabled: true
  level: INFO
  development: true
  output: log.txt