blockgen:
  endpoint: localhost:5002
  generator:
    profile: config/profile-blockgen.yaml

  monitoring:
    metrics:
      endpoint: :2113
      latency:
        sampler:
          type: blocktx
          ratio: 10
          sample-size: 100
          sample-period: 100000
        buckets:
          type: uniform
          max-latency: 5s
          bucket-count: 1000

logging:
  development: true
  enabled: true
  level: INFO
