sig-verification:
  endpoint: :5000
  prometheus:
    enabled: true
    latency-enabled: true
    endpoint: :2112
  scheme: "Ecdsa"
  parallel-executor:
    parallelism: 40
    batch-time-cutoff: 500ms
    batch-size-cutoff: 50
    channel-buffer-size: 50

logging:
  enabled: true
  level: INFO
  development: true
