orderer-submitter:
  channel-id: mychannel           # Overridden by ansible
  orderers:                       # Overridden by ansible
    - :7050
    - :7051
    - :7052
  monitoring:
    metrics:
      endpoint: :2112                                         # Overridden by ansible
  orderer-connection-profile: ./orderer-connection-profile.yaml   # Overridden by ansible
  messages: 1000000
  go-routines: 20
  message-size: 160
  signed-envelopes: true          # Overriden by ansible

logging:
  enabled: true
  level: INFO
  development: true
  output: log.txt