blockgen:
  endpoint: tokentestbed2.sl.cloud9.ibm.com:5002              # Overridden by ansible
  monitoring:
    metrics:
      endpoint: :2112                                         # Overridden by ansible
    latency:
      span-exporter: jaeger
      sampler:
        type: blocktx
        ratio: 10
        sample-size: 100
        sample-period: 100000
      endpoint: tokentestbed15.sl.cloud9.ibm.com:14268        # Overridden by ansible
      max-latency: 5s
      bucket-count: 1000
  generator:
    profile: ./profile-blockgen.yaml                          # Overridden by ansible
#    limits:
#      parallelism: 3
#      channel-buffer-size: 10

logging:
  enabled: true
  level: INFO
  development: true
  output: log.txt