sidecar:
  server:
    endpoint: :5000                                             # Overridden by ansible
    keep-alive:
      params:
        time: 300s
        timeout: 600s
      enforcement-policy:
        min-time: 60s
        permit-without-stream: false
  monitoring:
    metrics:
      endpoint: :2112                                         # Overridden by ansible
    latency:
      span-exporter: jaeger
      sampler:
        type: blocktx
        ratio: 10
        sample-size: 100
        sample-period: 100000
      endpoint: tokentestbed15.sl.cloud9.ibm.com:14268        # Overridden by ansible
      max-latency: 20s
      bucket-count: 1000
  orderer:
    endpoint: :7050                                             # Overridden by ansible
    channel-id: mychannel                                       # Overridden by ansible
    orderer-connection-profile: ./profile.yaml                  # Overridden by ansible
    reconnect: 10s
  committer:
    endpoint: :5002                                             # Overridden by ansible
    ledger-path: ./ledger                                       # Overridden by ansible
    output-channel-capacity: 20

logging:
  enabled: true
  level: INFO
  development: true
