apiVersion: 1
datasources:
  - name: 'Prometheus'
    #TODO: Replace UID and type with env vars in both yml and json
    uid: 'PBFA97CFB590B2093'
    type: 'prometheus'
    access: 'proxy'
    orgId: 1
    url: $_GF_PROMETHEUS_ENDPOINT
    httpMethod: GET
    isDefault: true
    version: 1
    editable: true
