Users:
  - UserName: issuer
    Password: issuerPWD
  - UserName: banka
    Password: bankaPWD
  - UserName: bankb
    Password: bankbPWD
  - UserName: dwadmin
    Password: dwadminPWD
  - UserName: alice
    Password: alicePWD
  - UserName: bob
    Password: bobPWD
  - UserName: charlie
    Password: charliePWD
  - UserName: dave
    Password: davePWD
  - UserName: seadmin
    Password: seadminPWD