name: profile1
description: some text
transaction:
  # number of serial numbers per transaction
  serialnumbersize:
    - probability: 1.0
      value: 2
  outputsize:
    - value: 1
      probability: 0.9
    - value: 0
      probability: 0.1
  # signature scheme
  signature:
    scheme: ecdsa
