name: profile1
description: some text
transaction:
  # number of serial numbers per transaction
  serialnumbersize:
    - probability: 1.0
      value: 2
  outputsize:
    - value: 2
      probability: 1.0
    - value: 0
      probability: 0
  # signature scheme
  signature:
    scheme: ecdsa
#conflicts:
#  statistical:
#    invalidsignatures: 0.0
#    doublespends: 0.0
#  scenario:
#    invalidsignatures:
#      - 1
#      - 3
#      - 5
#    doublespends:
#      - - 2-1
#        - 4-1
#        - 6-2
#      - - 7-1
#        - 7-2
#        - 8-1