name: profile1

description: some text

# block configuration
block:
  # number of blocks we generate
  # -1 indicates streaming infinite number of blocks
  count: -1
  # number of transactions per block
  size: 100

# transaction configuration
transaction:
  # number of serial numbers per transaction
  serialnumbersize:
    - value: 2
      probability: 1
  outputsize:
    - value: 1
      probability: 0.9
    - value: 0
      probability: 0.1
  # signature scheme
  signature:
    keypath:
      signingkey: /Users/lio/go/src/github.com/decentralized-trust-research/scalable-committer/myconfigs/signing.key
      verificationkey: /Users/lio/go/src/github.com/decentralized-trust-research/scalable-committer/myconfigs/sc_pubkey.pem
    scheme: ecdsa
# Introduce conflicts into our block stream
conflicts:
  statistical:
    invalidsignature: 0.0
    doublespends: 0.0