name: profile1
description: some text
transaction:
  # number of serial numbers per transaction
  serialnumbersize:
    - probability: 1.0
      value: 2
  outputsize:
    - value: 2
      probability: 1.0
    - value: 0
      probability: 0
  # signature scheme
  signature:
    scheme: ecdsa
