#
# SPDX-License-Identifier: Apache-2.0
#
---
  - name: Copy shardservice to remote machines and run
    hosts: shardsservices
    tasks:
      - name: Create directory for shardsservice
        file:
          path: ~/shardsservice
          state: directory
      - name: Copy shardsservice executable to remote machine
        copy:
          src: ../../bin/shardsservice
          dest: ~/shardsservice/
          owner: root
          group: root
          mode: a+x
      - name: Copy shared config to remote machine
        copy:
          src: "{{ '../../config/shared' }}"
          dest: ~/shardsservice/
          owner: root
          group: root
          mode: a+rw
      - name: Copy general config to remote machine
        copy:
          src: "{{ '../../config/config-shardsservice.yaml' }}"
          dest: ~/shardsservice/
          owner: root
          group: root
          mode: a+rw
      - name: Copy host specific config to remote machine
        copy:
          src: "{{ '../../config/config-' + inventory_hostname + '.yaml' }}"
          dest: ~/shardsservice/
          owner: root
          group: root
          mode: a+rw
      - name: Run shardsservice executable
        shell: ./shardsservice/shardsservice '{{ arg }}'
  - name: Copy sigverificationservice to remote machines and run
    hosts: sigverificationservices
    tasks:
      - name: Create directory for sigverificationservice
        file:
          path: ~/sigverificationservice
          state: directory
      - name: Copy sigverificationservice executable and config to remote machine
        copy:
          src: ../../bin/sigverificationservice
          dest: ~/sigverificationservice/
          owner: root
          group: root
          mode: a+x
      - name: Copy general config to remote machine
        copy:
          src: "{{ '../../config/config-sigverification.yaml' }}"
          dest: ~/sigverificationservice/
          owner: root
          group: root
          mode: a+rw
      - name: Copy host specific config to remote machine
        copy:
          src: "{{ '../../config/config-' + inventory_hostname + '.yaml' }}"
          dest: ~/sigverificationservice/
          owner: root
          group: root
          mode: a+rw
      - name: Run sigverificationservice executable
        shell: ./sigverificationservice/sigverificationservice '{{ arg }}'