#
# SPDX-License-Identifier: Apache-2.0
#
---
  - name: Create config destination folder
    hosts: localhost
    tasks:
      - name: Create tmp
        file:
          path: "{{dst_dir}}"
          state: directory
  - name: Create base configs and replace endpoints for all services
    hosts: localhost
    roles:
      - kwoodson.yedit
    tasks:
      - name: Create base config
        vars:
          coordinator_host: "{{hostvars[groups['coordinators'][0]]}}"
        include_tasks: ../subtasks/create-base-vars-for-group-config.yaml
        loop:
          - {filename: config-sigservice.yaml, target_hosts: sigservices, config_root: sig-verification}
          - {filename: config-shardsservice.yaml, target_hosts: shardsservices, config_root: shards-service}
          - {filename: config-coordinator.yaml, target_hosts: coordinators, config_root: coordinator}
          - {filename: config-blockgen.yaml, target_hosts: blockgens, config_root: blockgen, endpoint: "{{coordinator_host.ansible_host}}:{{coordinator_host.service_port}}"}
        loop_control:
          loop_var: config_item
          label: "{{config_item.target_hosts}}"
  - name: Further edit coordinator config
    hosts: localhost
    vars:
      coordinator_instance: "{{groups['coordinators'][0]}}"
      filepath: "{{dst_dir}}{{coordinator_instance}}-config-coordinator.yaml"
    tasks:
      - include_tasks: ../subtasks/edit-experiment-vars-for-coordinator-config.yaml
  - name: Further edit blockgen config/profile
    hosts: localhost
    vars:
      blockgen_instance: "{{groups['blockgens'][0]}}"
      # Where the file will be saved
      config_dst_filepath: "{{dst_dir}}{{blockgen_instance}}-config-blockgen.yaml"
      # Where we will read the file from
      profile_src_filepath: "{{src_dir}}profile-blockgen.yaml"
      # Where the file will be saved
      profile_dst_filepath: "{{dst_dir}}{{blockgen_instance}}-profile-blockgen.yaml"
      # Where the config file should point
      profile_path_reference: "{{hostvars[blockgen_instance].config_dir}}{{blockgen_instance}}-profile-blockgen.yaml"
    roles:
      - kwoodson.yedit
    tasks:
    - name: Edit blockgen profile filepath
      yedit:
        src: "{{config_dst_filepath}}"
        edits:
          - key: blockgen.generator.profile
            value: "{{profile_path_reference}}"
    - name: Copy base blockgen profile from local filesystem
      vars:
        mode: a+rw
        src_path: "{{profile_src_filepath}}"
        dst_path: "{{profile_dst_filepath}}"
      include_tasks: ../subtasks/copy-file.yaml
    - name: Set base setup to blockgen profile
      vars:
        filepath: "{{profile_dst_filepath}}"
      include_tasks: ../subtasks/edit-experiment-vars-for-blockgen-profile.yaml
