#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Create configs for shardsservice
  hosts: localhost
  vars:
    selected_hosts: "{{groups['shardsservices'] | d([]) | intersect(groups[target_hosts] | d([])) | map('extract', hostvars)}}"
  roles:
    - kwoodson.yedit
  tasks:
    - name: Create base config
      vars:
        config_root: shards-service
      include_tasks: ../subtasks/create-base-config.yaml
      when: "{{selected_hosts | length > 0}}"
