#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Create configs for blockgens
  hosts: localhost
  vars:
    selected_hosts: "{{groups['blockgens'] | d([]) | intersect(groups[target_hosts] | d([])) | map('extract', hostvars) | list}}"
  roles:
    - kwoodson.yedit
  tasks:
    - name: Create base config
      vars:
        config_root: blockgen
      include_tasks: ../subtasks/create-base-config.yaml
      when: "{{selected_hosts | length > 0}}"
    - name: Edit blockgen endpoint and profile filepath
      vars:
        coordinator_host: "{{groups['coordinators'] | map('extract', hostvars) | first}}"
      yedit:
        # Where the file will be saved
        src: "{{dst_dir}}/{{blockgen_instance.inventory_hostname}}/{{blockgen_instance.config}}"
        edits:
          - key: blockgen.generator.profile
            # Where the config file should point
            value: "{{blockgen_instance.config_dir}}/{{blockgen_instance.profile}}"
          - key: blockgen.endpoint
            value: "{{coordinator_host.ansible_host}}:{{coordinator_host.service_port}}"
      loop: "{{selected_hosts}}"
      loop_control:
        loop_var: blockgen_instance
    - name: Copy base blockgen profile from local filesystem
      vars:
        mode: a+rw
        # Where we will read the file from
        src_path: "{{src_dir}}/{{blockgen_instance.profile}}"
        # Where the file will be saved
        dst_path: "{{dst_dir}}/{{blockgen_instance.inventory_hostname}}/{{blockgen_instance.profile}}"
      include_tasks: ../subtasks/copy-file.yaml
      loop: "{{selected_hosts}}"
      loop_control:
        loop_var: blockgen_instance
    - name: Modify blockgen profile
      vars:
        filepath: "{{dst_dir}}/{{blockgen_instance.inventory_hostname}}/{{blockgen_instance.profile}}"
        small_txs: 1.0
        large_txs: 0.0
        invalidity_ratio: 0.0
        double_spends: 0.0
        block_size: 100
      yedit:
        src: "{{filepath}}"
        edits:
          - key: transaction.size
            append: true
            value:
              - value: 2
                probability: "{{small_txs}}"
              - value: 8
                probability: "{{large_txs}}"
          - key: conflicts.statistical.invalidsignature
            value: "{{invalidity_ratio}}"
          - key: conflicts.statistical.doublespends
            value: "{{double_spends}}"
          - key: block.size
            value: "{{block_size}}"
      loop: "{{selected_hosts}}"
      loop_control:
        loop_var: blockgen_instance
