#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Create configs for orderer listeners
  hosts: localhost
  vars:
    selected_hosts: "{{groups['ordererlisteners'] | d([]) | intersect(groups[target_hosts] | d([])) | map('extract', hostvars)}}"
  roles:
      - kwoodson.yedit
  tasks:
    - name: Copy configs
      vars:
        config_root: orderer-listener
      include_tasks: ../subtasks/create-orderer-client-config.yaml
    - name: Edit listener config
      vars:
        config_dst_filepath: "{{dst_dir}}/{{ordererlistener_instance.inventory_hostname}}/{{ordererlistener_instance.config}}"
        orderer_hosts: "{{groups['orderingservices'] | map('extract', hostvars)}}"
        orderer_endpoints: "{{orderer_hosts | map(attribute='ansible_host') | zip(orderer_hosts | map(attribute='service_port')) | map('join', ':')}}"
      yedit:
        src: "{{config_dst_filepath}}"
        edits:
          - key: orderer-listener.orderer
            value: "{{orderer_endpoints | first}}"
      loop: "{{selected_hosts}}"
      loop_control:
        loop_var: ordererlistener_instance