#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Create config destination folder
  hosts: localhost
  tasks:
    - name: Create tmp
      file:
        path: "{{dst_dir}}"
        state: directory
    - name: Create file
      file:
        path: "{{dst_dir}}/ui-config.yaml"
        state: touch
- name: Create base configs and replace endpoints for all services
  hosts: localhost
  vars:
    filepath: "{{dst_dir}}/ui-config.yaml"
    topology_name: default
    log_level: WARNING
  roles:
    - kwoodson.yedit
  tasks:
    - name: Prepare FSC endpoints
      set_fact:
        fsc_endpoints: "{{fsc_endpoints | d([])  + [{
          'name': instance.inventory_hostname,
          'endpoint': instance.ansible_host + ':' + (instance.ops_port | string)
        }]}}"
      loop: "{{groups['fscservices'] | d([]) | map('extract', hostvars) | list}}"
      loop_control:
        loop_var: instance
      when: instance.ops_port | d(0) > 0
    - name: Create UI config
      yedit:
        src: "{{filepath}}"
        edits:
          - key: fsc-endpoints
            value: "{{fsc_endpoints | d([])}}"