#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Create config destination folder
  hosts: localhost
  vars:
    yaml_filepath: "{{dst_dir}}/ui-config.yaml"
    json_filepath: "{{dst_dir}}/ui-config.json"
  roles:
    - kwoodson.yedit
  tasks:
    - name: Check ports
      shell: 'ping -c1 {{item.ops_host | d(item.ansible_host)}} | sed -nE "s/^PING[^(]+\(([^)]+)\).*/\1/p"'
      register: stdout
      with_items: "{{groups['all'] | map('extract', hostvars) | list}}"
      when: item.ansible_host | d('') | length > 0 and item.service_port | d(0) | int > 0
    - set_fact:
        ip_addresses: "{{ip_addresses | default({}) | combine ({ (item.item.ops_host | d(item.item.ansible_host)) : item.stdout | d('') })}}"
      with_items: "{{stdout.results}}"
    - name: Create tmp
      file:
        path: "{{dst_dir}}"
        state: directory
    - name: Create files
      file:
        path: "{{filepath}}"
        state: touch
      loop:
        - "{{yaml_filepath}}"
        - "{{json_filepath}}"
      loop_control:
        loop_var: filepath
    - name: Prepare FSC endpoints
      set_fact:
        fsc_endpoints: "{{fsc_endpoints | d([])  + [{
          'name': instance.inventory_hostname,
          'auditor': instance.auditor | d(false),
          'certifier': instance.certifier | d(false),
          'issuer': instance.issuer_identities | d([]) | length > 0,
          'endorser': instance.endorser | d(false),
          'endpoint': ip_addresses[instance.ops_host | d(instance.ansible_host)] + ':' + (instance.ops_port | string)
        }]}}"
      loop: "{{groups['fscservices'] | d([]) | map('extract', hostvars) | list}}"
      loop_control:
        loop_var: instance
      when: instance.ops_port | d(0) > 0
    - name: Create UI config YAML
      yedit:
        src: "{{yaml_filepath}}"
        edits:
          - key: fsc-endpoints
            value: "{{fsc_endpoints | d([])}}"
    - name: Create UI config JSON
      copy:
        content: "{{ {'fscEndpoints': fsc_endpoints | d([]) } | to_json }}"
        dest: "{{json_filepath}}"
