#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Transfer config to destination server
  hosts: "{{target_hosts}}"
  vars:
    mode: a+rw
    dst_dir: "{{config_dir}}"
  tasks:
    - vars:
        filename: "{{inventory_hostname}}-{{name}}"
      include_tasks: ../subtasks/copy-file.yaml
      loop: "{{filenames}}"
      loop_control:
        loop_var: name

