#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Transfer config to destination server
  hosts: "{{target_hosts}}"
  vars:
    mode: a+rw
    dst_dir: "{{config_dir}}"
    hostvar: "{{hostvars[inventory_hostname]}}"
  tasks:
    - vars:
        src_filename: "{{hostvar.config}}"
        filename: "{{inventory_hostname}}-{{src_filename}}"
      include_tasks: ../subtasks/copy-file.yaml
      when: src_filename | length > 0
      loop:
        - "{{hostvar.config | d()}}"
        - "{{hostvar.block_profile | d()}}"
      loop_control:
        loop_var: src_filename

