#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Create Prometheus-config destination folder
  hosts: localhost
  tasks:
    - name: Create directory
      file:
        path: "{{dst_dir}}"
        state: directory
    - name: Create Prometheus-config file from template
      vars:
        fsc_hosts: "{{groups['fscservices'] | d([]) | map('extract', hostvars) | selectattr('web_port', 'defined') | list}}"
        fsc_endpoints: "{{fsc_hosts | map(attribute='ansible_host') | zip(fsc_hosts | map(attribute='web_port')) | map('join', ':') | list}}"
        orderer_hosts: "{{groups['orderingservices'] | d([]) | map('extract', hostvars) | selectattr('ops_port', 'defined') | list}}"
        orderer_endpoints: "{{orderer_hosts | map(attribute='ansible_host') | zip(orderer_hosts | map(attribute='ops_port')) | map('join', ':') | list}}"
        peer_hosts: "{{groups['peerservices'] | d([]) | map('extract', hostvars) | selectattr('ops_port', 'defined') | list}}"
        peer_endpoints: "{{peer_hosts | map(attribute='ansible_host') | zip(peer_hosts | map(attribute='ops_port')) | map('join', ':') | list}}"
        committer_hosts: "{{groups['coordinators'] | d([]) | union(groups['sigservices'] | d([])) | union(groups['shardsservices'] | d([])) | map('extract', hostvars) | selectattr('prometheus_exporter_port', 'defined') | list}}"
        committer_endpoints: "{{committer_hosts | map(attribute='ansible_host') | zip(committer_hosts | map(attribute='prometheus_exporter_port')) | map('join', ':') | list}}"
        client_hosts: "{{groups['clients'] | map('extract', hostvars) | selectattr('prometheus_exporter_port', 'defined') | list}}"
        client_endpoints: "{{client_hosts | map(attribute='ansible_host') | zip(committer_hosts | map(attribute='prometheus_exporter_port')) | map('join', ':') | list}}"
      template:
        src: ../templates/prometheus.yml.j2
        dest: "{{dst_dir}}/prometheus.yml"