#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Transfer creds to sidecar clients
  hosts: sidecarclients,sidecars,orderersubmitters,ordererlisteners
  vars:
    mode: a+rw
    orderer: "{{groups['orderingservices'] | map('extract', hostvars) | first}}"
    dst_dir: "{{creds_dir}}"
  tasks:
    - vars:
        src_dir: "{{item.src_dir}}"
        filename: "{{item.filename | d('')}}"
      include_tasks: ../subtasks/copy-file.yaml
      loop:
        - {src_dir: "{{input_creds_path}}/orgs/ordererOrganizations/orderer.org/orderers/{{orderer.orderer_name}}.orderer.org/tls", filename: "ca.crt"}
        - {src_dir: "{{input_creds_path}}/orgs/peerOrganizations/org1.com/users/User1@org1.com/msp"}
        - {src_dir: "{{input_config_path}}", filename: "{{orderer.config}}"}

