#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Transfer sidecar client config to destination server
  hosts: "{{target_hosts}}:&sidecarclients"
  vars:
    topology_dir: "fabric.{{topology_name}}"
  tasks:
    - include_tasks: ../subtasks/transfer-base-config.yaml
    - vars:
        node_fqn: "{{inherit_peer}}.{{hostvars[inherit_peer].organization | lower}}.{{hostvars[inherit_peer].domain}}"
        node_type: peers
        include_root_ca_certs: true
      include_tasks: ../subtasks/transfer-node-creds.yaml
      when: include_creds | d(false) == true
    - vars:
        endorser: "{{hostvars[inherit_endorser]}}"
        topology_dir: "fabric.{{topology_name}}"
        node_domain: "{{endorser.organization | lower}}.{{endorser.domain}}"
        node_type: peers
      include_tasks: ../subtasks/transfer-fsc-node-creds.yaml
      when: include_creds | d(false) == true and profile | d('') | length > 0 and inherit_endorser | d('') | length > 0
    - vars:
        node_type: peers
        node_name: "{{inherit_peer}}"
        file_type: profile
      include_tasks: ../subtasks/transfer-node-config-profile.yaml
      when: include_configs | d(false) == true
