#
# SPDX-License-Identifier: Apache-2.0
#
---

- name: Transfer configs and creds to peers
  hosts: "{{target_hosts}}:&peerservices"
  vars:
    topology_dir: "fabric.{{topology_name}}"
  tasks:
    - vars:
        node_fqn: "{{instance.node_fqn}}"
        node_type: "{{instance.node_type}}"
        include_root_ca_certs: true
      include_tasks: ../subtasks/transfer-node-creds.yaml
      when: include_creds | d(false) == true
      loop:
        - {'node_type': 'peers', 'node_fqn': '{{inventory_hostname}}.{{organization | lower}}.{{domain}}'}
        - {'node_type': 'users', 'node_fqn': 'Admin@{{organization | lower}}.{{domain}}'}
      loop_control:
        loop_var: instance
    - vars:
        node_type: peers
        node_name: "{{inventory_hostname}}"
        file_type: config
      include_tasks: ../subtasks/transfer-node-config-profile.yaml
      when: include_configs | d(false) == true
    - name: "Transfer genesis blocks for {{inventory_hostname}}"
      include_tasks: ../subtasks/transfer-genesis-blocks.yaml
      when: include_genesis | d(false) == true
    - name: "Transfer chaincode package for {{inventory_hostname}}"
      vars:
        src_dir: "{{orderer_artifacts_path}}/token/chaincodes"
        dst_dir: "{{config_dir}}/token"
      include_tasks: ../subtasks/copy-file.yaml
      when: include_chaincode | d(false) == true and groups['fscservices'] | d([]) | length > 0
    - name: "Transfer topology for {{inventory_hostname}}"
      vars:
        src_dir: "{{orderer_artifacts_path}}"
        dst_dir: "{{config_dir}}"
        filename: topology.yaml
      include_tasks: ../subtasks/copy-file.yaml
      when: include_configs | d(false) == true
    - name: "Replace double curly brackets in files"
      # Needed in order to avoid parsing problems
      replace:
        dest: "{{config_dir}}/topology.yaml"
        regexp: "{{'{{'}}"
        replace: open_curly
      when: include_configs | d(false) == true


