#
# SPDX-License-Identifier: Apache-2.0
#
---

- name: Transfer configs and creds to peers
  hosts: "{{target_hosts}}:&peerservices"
  tasks:
    - vars:
        node_type: peers
        node_name: "{{inventory_hostname}}"
        file_type: config
      include_tasks: ../subtasks/transfer-node-config-profile.yaml
      when: include_configs | d(false) == true
    - vars:
        node_fqn: "{{instance.node_fqn}}"
        node_type: "{{instance.node_type}}"
        include_root_ca_certs: true
      include_tasks: ../subtasks/transfer-node-creds.yaml
      when: include_creds | d(false) == true
      loop:
        - {'node_type': 'peers', 'node_fqn': '{{inventory_hostname}}.{{organization | lower}}.{{domain}}'}
        - {'node_type': 'users', 'node_fqn': 'Admin@{{organization | lower}}.{{domain}}'}
      loop_control:
        loop_var: instance
    - name: "Transfer genesis blocks for {{inventory_hostname}}"
      include_tasks: ../subtasks/transfer-genesis-blocks.yaml
      when: include_genesis | d(false) == true

