#
# SPDX-License-Identifier: Apache-2.0
#
---
# ansible-playbook -i ./ansible/inventory/hosts.yaml ./ansible/playbooks/60-config-experiment.yaml --extra-vars '{"sig_verifiers": 3, "shard_servers": 3, "large_txs": 0.0, "validity_ratio": 1.0}'

  - name: Create tmp folder
    hosts: localhost
    tasks:
      - name: Create tmp
        file:
          path: ./tmp
          state: directory

  - name: Create coordinator config
    vars:
      coordinator_config_src: "../../{{src_config_dir}}/config-coordinator.yaml"
      shard_servers: 3
      shard_server_port: 5001
      num_shards: 1
      sig_verifier_port: 5000
      sig_verifiers: 3
    hosts: localhost
    roles:
      - kwoodson.yedit
    tasks:
      - name: Copy coordinator config
        copy:
          src: "{{coordinator_config_src}}"
          dest: ./tmp/config-coordinator.yaml
      - name: Delete all default shard servers
        yedit:
          src: ./tmp/config-coordinator.yaml
          key: coordinator.shards-servers.servers
          state: absent
      - name: Add shard servers
        yedit:
          src: ./tmp/config-coordinator.yaml
          key: coordinator.shards-servers.servers
          append: true
          value:
            endpoint: "{{hostvars[item].ansible_host}}:{{shard_server_port}}"
            num-shards: "{{num_shards}}"
        loop: "{{groups['shardsservices'] | default([])}}"
        when: idx < {{shard_servers}}
        loop_control:
          index_var: idx
      - name: Delete all default sig-verifiers
        yedit:
          src: ./tmp/config-coordinator.yaml
          key: coordinator.sig-verifiers.endpoints
          state: absent
      - name: Add sig-verifiers
        yedit:
          src: ./tmp/config-coordinator.yaml
          key: coordinator.sig-verifiers.endpoints
          append: true
          value: "{{hostvars[item].ansible_host}}:{{sig_verifier_port}}"
        loop: "{{groups['sigservices'] | default([])}}"
        when: idx < {{sig_verifiers}}
        loop_control:
          index_var: idx

  - name: Create blockgen profile
    vars:
      blockgen_profile_src: "../../{{src_config_dir}}/profile-blockgen.yaml"
      small_txs: 1.0
      large_txs: 0.0
      invalidity_ratio: 0.0
      double_spends: 0.0
      block_size: 100
    hosts: localhost
    roles:
      - kwoodson.yedit
    tasks:
      - name: Copy blockgen config
        copy:
          src: "{{blockgen_profile_src}}"
          dest: ./tmp/profile-blockgen.yaml
      - name: Delete all SN sizes
        yedit:
          src: ./tmp/profile-blockgen.yaml
          key: transaction.size
          state: absent
      - name: Add TXs with 2 SNs
        yedit:
          src: ./tmp/profile-blockgen.yaml
          key: transaction.size
          append: true
          value:
            value: 2
            probability: "{{small_txs}}"
      - name: Add TXs with 8 SNs
        yedit:
          src: ./tmp/profile-blockgen.yaml
          key: transaction.size
          append: true
          value:
            value: 8
            probability: "{{large_txs}}"
      - name: Edit validity ratio / block size
        yedit:
          src: ./tmp/profile-blockgen.yaml
          edits:
            - key: conflicts.statistical.invalidsignature
              value: "{{invalidity_ratio}}"
            - key: conflicts.statistical.doublespends
              value: "{{double_spends}}"
            - key: block.size
              value: "{{block_size}}"

  - name: Create blockgen config
    vars:
      blockgen_config_src: "../../{{src_config_dir}}/config-blockgen.yaml"
      coordinator_endpoint: ":5002"
    hosts: localhost
    roles:
      - kwoodson.yedit
    tasks:
      - name: Copy blockgen config
        copy:
          src: "{{blockgen_config_src}}"
          dest: ./tmp/config-blockgen.yaml
      - name: Edit endpoint
        yedit:
          src: ./tmp/config-blockgen.yaml
          edits:
            - key: blockgen.endpoint
              value: "{{coordinator_endpoint}}"

  - name: Copy coordinator config to remote
    hosts: coordinators
    vars:
      configpath: config
      filenames:
        - config-coordinator.yaml
    tasks:
      - include: ../roles/copy-config.yaml
  - name: Copy blockgen config to remote
    hosts: blockgens
    vars:
      configpath: config
      filenames:
        - config-blockgen.yaml
        - profile-blockgen.yaml
    tasks:
      - include: ../roles/copy-config.yaml

#  - name: Clean up
#    hosts: localhost
#    tasks:
#      - name: Remove tmp
#        file:
#          path: ./tmp
#          state: absent