#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Start shard servers
  hosts: "{{target_hosts}}:&shardsservices"
  tasks:
    - vars:
        service_name: shardsservice
        wait_until_running: true
        options:
          configs: "{{config_dir}}/{{config}}"
      include_tasks: ../subtasks/start-server.yaml
