#
# SPDX-License-Identifier: Apache-2.0
#
---
  - name: Start sig verifiers
    vars:
      sig_verifiers: 3
      service_name: sigservice
      config: config-sigservice.yaml
      only_kill: false
    hosts: sigservices[0:{{sig_verifiers - 1}}]
    tasks:
      - include_tasks: ../subtasks/start-server.yaml
  - name: Start shard servers
    vars:
      shard_servers: 3
      service_name: shardsservice
      config: config-shardsservice.yaml
      only_kill: false
    hosts: shardsservices[0:{{shard_servers - 1}}]
    tasks:
      - include_tasks: ../subtasks/start-server.yaml
  - name: Start coordinator
    vars:
      service_name: coordinator
      config: config-coordinator.yaml
      only_kill: false
    hosts: coordinators
    tasks:
      - include_tasks: ../subtasks/start-server.yaml



