#
# SPDX-License-Identifier: Apache-2.0
#
---
  - name: Start sig verifiers
    vars:
      target_hosts: sigservices
      service_name: sigservice
      sigservice_instances: "{{groups[target_hosts] | d([]) | length}}"
    hosts: sigservices[0:{{sigservice_instances | int - 1}}]
    tasks:
      - include_tasks: ../subtasks/start-server.yaml
        when: service_name in start
  - name: Start shard servers
    vars:
      target_hosts: shardsservices
      service_name: shardsservice
      shardsservice_instances: "{{groups[target_hosts] | d([]) | length}}"
    hosts: shardsservices[0:{{shardsservice_instances | int - 1}}]
    tasks:
      - include_tasks: ../subtasks/start-server.yaml
        when: service_name in start
  - name: Start coordinator
    vars:
      service_name: coordinator
    hosts: coordinators
    tasks:
      - include_tasks: ../subtasks/start-server.yaml
        when: service_name in start
  - name: Start mock coordinator
    vars:
      service_name: mockcoordinator
    hosts: coordinators
    tasks:
      - include_tasks: ../subtasks/start-server.yaml
        when: service_name in start
  - name: Start block generator
    vars:
      target_hosts: blockgens
      service_name: blockgen stream
      blockgen_instances: "{{groups[target_hosts] | d([]) | length}}"
    hosts: blockgens[0:{{blockgen_instances | int - 1}}]
    tasks:
      - vars:
          env:
            - "GOGC=20000"
        include_tasks: ../subtasks/start-server.yaml
        when: service_name in start
  - name: Start mock orderers
    vars:
      target_hosts: orderingservices
      service_name: mockorderingservice
      orderingservice_instances: "{{groups[target_hosts] | length}}"
      opts:
        endpoint: "{{ansible_host}}:{{service_port}}"
    hosts: orderingservices[0:{{orderingservice_instances | int - 1}}]
    tasks:
      - include_tasks: ../subtasks/start-server.yaml
        when: service_name in start
  - name: Start sidecar
    vars:
      service_name: sidecar
    hosts: sidecars
    tasks:
      - include_tasks: ../subtasks/start-server.yaml
        when: service_name in start
  - name: Start sidecar client
    vars:
      target_hosts: sidecarclients
      service_name: sidecarclient
      sidecarclient_instances: "{{groups[target_hosts] | d([]) | length}}"
    hosts: sidecarclients[0:{{sidecarclient_instances | int - 1}}]
    tasks:
      - vars:
          env:
            - "GOGC=20000"
        include_tasks: ../subtasks/start-server.yaml
        when: service_name in start
  - name: Start orderers
    vars:
      target_hosts: orderingservices
      service_name: orderer
      orderingservice_instances: "{{groups[target_hosts] | d([]) | length}}"
    hosts: orderingservices[0:{{orderingservice_instances | int - 1}}]
    tasks:
      - vars:
          config: ''
          env:
            - FABRIC_CFG_PATH={{config_dir}}
            - ORDERER_GENERAL_LOCALMSPID=Orderer
            - ORDERER_GENERAL_LOCALMSPDIR={{creds_dir}}/msp
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_LISTENPORT={{service_port}}
            - ORDERER_GENERAL_GENESISFILE={{genesis_dir}}/genesisblock
            - ORDERER_GENERAL_BOOTSTRAPFILE={{genesis_dir}}/genesisblock
            - ORDERER_GENERAL_TLS_ENABLED=true
            - ORDERER_GENERAL_TLS_PRIVATEKEY={{creds_dir}}/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE={{creds_dir}}/tls/server.crt
            - ORDERER_GENERAL_TLS_ROOTCAS=[{{creds_dir}}/tls/ca.crt]
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE={{creds_dir}}/tls/server.crt
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY={{creds_dir}}/tls/server.key
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[{{creds_dir}}/tls/ca.crt]
            - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:{{ops_port}}
            - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:{{admin_port}}
            - ORDERER_FILELEDGER_LOCATION={{ledger_dir}}
            - ORDERER_CONSENSUS_WALDIR={{ledger_dir}}/etcdraft/wal
            - ORDERER_CONSENSUS_SNAPDIR={{ledger_dir}}/snapshot
        include_tasks: ../subtasks/start-server.yaml
        when: service_name in start
  - name: Start orderer listeners
    vars:
      target_hosts: ordererlisteners
      service_name: ordererlistener
      ordererlistener_instances: "{{groups[target_hosts] | d([]) | length}}"
      orderer_hosts: "{{groups['orderingservices'] | map('extract', hostvars)}}"
      orderer_endpoints: "{{orderer_hosts | map(attribute='ansible_host') | zip(orderer_hosts | map(attribute='service_port')) | map('join', ':')}}"
      orderer_endpoint: "{{orderer_endpoints | last}}"
      channel_id: mychannel
    hosts: ordererlisteners[0:{{ordererlistener_instances | int - 1}}]
    tasks:
      - vars:
          var_prefix: "-"
          opts:
            creds-path: "{{creds_dir}}"
            config-path: "{{creds_dir}}"
            root-ca-path: "{{creds_dir}}/ca.crt"
            quiet: true
            server: "{{orderer_endpoint}}"
            channel-id: "{{channel_id}}"
            prometheus-endpoint: ":{{prometheus_exporter_port}}"
        include_tasks: ../subtasks/start-server.yaml
        when: service_name in start
  - name: Start orderer submitters
    vars:
      target_hosts: orderersubmitters
      service_name: orderersubmitter
      orderersubmitter_instances: "{{groups[target_hosts] | d([]) | length}}"
      orderer_hosts: "{{groups['orderingservices'] | map('extract', hostvars)}}"
      orderer_endpoints: "{{orderer_hosts | map(attribute='ansible_host') | zip(orderer_hosts | map(attribute='service_port')) | map('join', ':')}}"
      orderer_endpoint: "{{orderer_endpoints | first}}"
      messages: 1000000
      message_size: 160
      connections: 1
      streams_per_connection: 1
      channel_id: mychannel
    hosts: orderersubmitters[0:{{orderersubmitter_instances | int - 1}}]
    tasks:
      - vars:
          var_prefix: "-"
          opts:
            creds-path: "{{creds_dir}}"
            config-path: "{{creds_dir}}"
            root-ca-path: "{{creds_dir}}/ca.crt"
            messages: "{{messages}}"
            size: "{{message_size}}"
            channel-id: "{{channel_id}}"
            orderers: "{{range(connections | int) | product([orderer_endpoint]) | map('last') | join(',')}}"
            goroutines: "{{(streams_per_connection | int) * (connections | int)}}"
            prometheus-endpoint: ":{{prometheus_exporter_port}}"
          env:
            - "GOGC=20000"
        include_tasks: ../subtasks/start-server.yaml
        when: service_name in start
