#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Start mock coordinator
  vars:
    service_name: mockcoordinator
    config: config-coordinator.yaml
    only_kill: false
  hosts: coordinators
  tasks:
    - include_tasks: ../subtasks/start-server.yaml



