#
# SPDX-License-Identifier: Apache-2.0
#
---
- hosts: localhost
  vars:
    target_instance: "{{hostvars[target_host]}}"
    target_endpoint: "http://{{target_instance.ansible_host}}:{{target_instance.ops_port}}"
  tasks:
    - name: Log in
      uri:
        url: "{{target_endpoint}}/login"
        method: POST
        body:
          username: "{{user}}"
          password: "{{user}}"
        body_format: json
      register: login_result
    - set_fact:
        token: "{{login_result.json.token}}"
    - name: "Issue {{value}} tokens to {{recipient}}"
      uri:
        url: "{{target_endpoint}}/zkat/issue"
        method: POST
        body:
          value: "{{value}}"
          recipient: "{{recipient}}"
        body_format: form-urlencoded
        headers:
          Authorization: "Bearer {{token}}"
      when: action == 'issue'
      register: result
    - debug: var=result.json
      when: action == 'issue'
    - name: "Initiate payment of {{value}} tokens to {{recipient}}"
      uri:
        url: "{{target_endpoint}}/zkat/payments/initiation"
        method: POST
        body:
          value: "{{value}}"
          recipient: "{{recipient}}"
          nonce: "{{nonce}}"
        body_format: form-urlencoded
        headers:
          Authorization: "Bearer {{token}}"
      when: action == 'initiate'
      register: result
    - debug:
        msg:
          - "{{result.json}}"
          - 'curl -X POST -H "Content-Type: application/x-www-form-urlencoded;charset=UTF-8" -H "Authorization: Bearer {{token}}" -d "value={{value}}&recipient={{recipient}}&nonce={{nonce}}" {{target_endpoint}}/zkat/payments/initiation'
      when: action == 'initiate'
    - name: "Accept payment of {{value}} tokens to {{recipient}}"
      uri:
        url: "{{target_endpoint}}/zkat/payments/transfer"
        method: POST
        body:
          value: "{{value}}"
          recipient: "{{recipient}}"
          nonce: "{{nonce}}"
        body_format: form-urlencoded
        headers:
          Authorization: "Bearer {{token}}"
      when: action == 'transfer'
      register: result
    - debug:
        msg:
          - "{{result.json}}"
          - 'curl -X POST -H "Content-Type: application/x-www-form-urlencoded;charset=UTF-8" -H "Authorization: Bearer {{token}}" -d "value={{value}}&recipient={{recipient}}&nonce={{nonce}}" {{target_endpoint}}/zkat/payments/transfer'
      when: action == 'transfer'
    - name: "Get balance of {{target_host}}"
      uri:
        url: "{{target_endpoint}}/zkat/balance?user={{user}}"
        method: GET
        headers:
          Authorization: "Bearer {{token}}"
      when: action == 'balance'
      register: result
    - debug: var=result.json
      when: action == 'balance'
    - name: "Get all payments of {{target_host}}"
      uri:
        url: "{{target_endpoint}}/zkat/intermediary/payments?user=alice"
        method: GET
        headers:
          Authorization: "Bearer {{token}}"
      when: action == 'payments'
      register: result
    - debug: var=result.json
      when: action == 'payments'
    - name: "Get all payments of {{target_host}}"
      uri:
        url: "{{target_endpoint}}/zkat/payments/status?nonce={{nonce}}"
        method: GET
        headers:
          Authorization: "Bearer {{token}}"
      when: action == 'status'
      register: result
    - debug: var=result.json
      when: action == 'status'
    - name: "Get all payments of {{target_host}}"
      uri:
        url: "{{target_endpoint}}/zkat/intermediary/ownerWalletIDs"
        method: GET
        headers:
          Authorization: "Bearer {{token}}"
      when: action == 'wallets'
      register: result
    - debug: var=result.json
      when: action == 'wallets'
    - name: "Get all validation records of {{target_host}}"
      uri:
        url: "{{target_endpoint}}/zkat/settlement/validationRecords"
        method: GET
        headers:
          Authorization: "Bearer {{token}}"
      when: action == 'records'
      register: result
    - debug: var=result.json
      when: action == 'records'
