#
# SPDX-License-Identifier: Apache-2.0
#
---
- hosts: localhost
  vars:
    target_instances: "{{groups['clients'] | d([]) | map('extract', hostvars) | selectattr('limiter_port', 'defined') | list}}"
  tasks:
    - name: "Limiting rate to {{limit}} TPS"
      uri:
        url: "http://{{target_instance.ansible_host}}:{{target_instance.limiter_port}}/setLimits"
        method: POST
        body:
          limit: "{{limit}}"
        body_format: json
      loop: "{{target_instances}}"
      loop_control:
        loop_var: target_instance
