#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Modify (in place) experiment-related variables
  hosts: localhost
  roles:
    - kwoodson.yedit
  tasks:
    - name: Modify sidecar config
      vars:
        sidecar_instance: "{{groups['sidecars'] | first}}"
        filepath: "{{src_dir}}/{{sidecar_instance}}-{{hostvars[sidecar_instance].config}}"
      include_tasks: ../subtasks/edit-experiment-vars-for-sidecar-config.yaml
