#
# SPDX-License-Identifier: Apache-2.0
#
---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Check ports
      shell: "nmap {{item.ansible_host}} -p {{item.service_port}} | grep {{item.service_port}}/tcp"
      register: stdout
      with_items: "{{groups['all'] | map('extract', hostvars) | list}}"
      when: item.ansible_host | d('') | length > 0 and item.service_port | d(0) | int > 0
    - set_fact:
        port_statuses: "{{port_statuses | d([]) + [{
        'name': item.item.inventory_hostname,
        'endpoint': (item.item.ansible_host | d('')) + ':' + (item.item.service_port | d(0) | string),
        'status': item.stdout | d('')
        }]}}"
      with_items: "{{stdout.results}}"
    - debug: var=port_statuses
