#
# SPDX-License-Identifier: Apache-2.0
#
---
- hosts: "{{target_hosts}}:&shardsservices"
  tasks:
    - name: Clear shard db
      file:
        state: absent
        path: "{{db_dir}}"
- hosts: "{{target_hosts}}:&orderingservices"
  tasks:
    - name: Clear orderer cache
      vars:
        top_dir: "{{config_dir}}/fabric.{{topology_name | d('')}}/orderers/{{organization}}.{{inventory_hostname}}"
      file:
        state: absent
        path: "{{dir}}/"
      loop:
        - "{{top_dir}}/etcdraft"
        - "{{top_dir}}/system"
      loop_control:
        loop_var: dir
- hosts: "{{target_hosts}}:&sidecars"
  tasks:
    - name: Clear sidecar ledger
      file:
        state: absent
        path: "{{config_dir}}/ledger"
- hosts: "{{target_hosts}}:&peerservices"
  tasks:
    - name: Clear peer filesystem
      file:
        state: absent
        path: "{{config_dir}}/fabric.{{topology_name | d('')}}/peers/{{organization}}.{{inventory_hostname}}/filesystem/"
- hosts: "{{target_hosts}}:&fscservices"
  tasks:
    - name: Clear FSC-node kvs
      file:
        state: absent
        path: "{{path}}"
      loop:
        - "{{config_dir}}/fsc/nodes/{{inventory_hostname}}/fabric.{{topology_name | d('')}}"
        - "{{config_dir}}/fsc/nodes/{{inventory_hostname}}/kvs"
      loop_control:
        loop_var: path
- name: Clean all generated files
  hosts: "{{target_hosts}}"
  tasks:
    - file:
        state: absent
        path: "{{dir}}/"
      when: dir is defined and dir | length > 0
      loop:
        - "{{config_dir if include_configs | d(false) == true else ''}}"
        - "{{binary_dir if include_bins | d(false) == true else ''}}"
      loop_control:
        loop_var: dir

