#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Clean all generated files
  hosts: "{{target_hosts}}"
  tasks:
  - file:
      state: absent
      path: "{{dir}}/"
    when: dir is defined and dir | length > 0
    loop:
      - "{{config_dir if include_configs is defined and include_configs == 'true' else ''}}"
      - "{{creds_dir if include_configs is defined and include_configs == 'true' else ''}}"
      - "{{genesis_dir if include_configs is defined and include_configs == 'true' else ''}}"
      - "{{ledger_dir}}"
      - "{{binary_dir if include_bins is defined and include_bins == 'true' else ''}}"
    loop_control:
      loop_var: dir
