sidecar:
  orderer:
    connection:
      endpoints:
        - localhost:%d
    channel-id: mychannel
  committer:
    endpoint: localhost:%d
  ledger:
    path: %s
  monitoring:
    server:
      endpoint: localhost:%d
  server:
    endpoint: localhost:%d

logging:
  enabled: true
  level: info
  caller: true
  development: true
  output: %s
