orderer-submitter:
  channel-id: mychannel
  orderers:
    - localhost:7051
  prometheus:
    endpoint: :2112
  orderer-connection-profile: orderer-connection-profile.yaml
  messages: 10000000
  go-routines: 100
  message-size: 240
  signed: false