orderer-submitter:
  channel-id: mychannel
  orderers:
    - localhost:7051
  prometheus:
    endpoint: :2112
  # enables the remote limiter controller; if empty it is disabled
  remote-controller-listener: localhost:6997
  orderer-connection-profile: orderer-connection-profile.yaml
  messages: 10000000
  go-routines: 100
  message-size: 240
  signed: false
  orderer-type: etcdraft