server:
  endpoint: {{ .ServerEndpoint | default "localhost:0" }}
monitoring:
  server:
    endpoint: {{ .MetricsEndpoint | default "localhost:0" }}

verifier:
  endpoints:
    {{- range .Endpoints.Verifier }}
    - {{ . }}
    {{- end }}
validator-committer:
  endpoints:
   {{- range .Endpoints.VCService }}
    - {{ . }}
   {{- end }}

dependency-graph:
  num-of-local-dep-constructors: 1
  waiting-txs-limit: 10_000
  num-of-workers-for-global-dep-manager: 1
  # Add monitoring configuration here if applicable
per-channel-buffer-size-per-goroutine: 10

logging:
  enabled: {{ .Logging.Enabled }}
  level: {{ .Logging.Level }}
  caller: {{ .Logging.Caller }}
  development: {{ .Logging.Development }}
  output: {{ .Logging.Output }}
  name: coordinator
