coordinator-service:
  server:
    endpoint: {{ .ServerEndpoint | default "localhost:0" }}
  monitoring:
    server:
      endpoint: {{ .MetricsEndpoint | default "localhost:0" }}

  sign-verifier:
    server: 
      {{- range .Endpoints.Verifier }}
      - endpoint: {{ . }}
      {{- end }}
  validator-committer:
    server: 
     {{- range .Endpoints.VCService }}
      - endpoint: {{ . }}
      {{- end }}
  dependency-graph:
    num-of-local-dep-constructors: 1
    waiting-txs-limit: 10000
    num-of-workers-for-global-dep-manager: 1
    # Add monitoring configuration here if applicable
  per-channel-buffer-size-per-goroutine: 10

{{ template "loggingBlock" . }}
