mock-ordering-service:
  servers:
    {{- range .Endpoints.Orderer }}
    - endpoint: {{ . }}
    {{- end }}
  block-size: {{ .BlockSize }}
  block-timeout: {{ .BlockTimeout }}
  config-block-path: {{ .ConfigBlockPath }}
  send-config-block: true

{{ template "loggingBlock" . }}
