query-service:
  # Configuration for the server
  server:
    # The server's endpoint configuration
    endpoint: {{ .ServerEndpoint | default "localhost:0" }}
  monitoring:
    server:
      endpoint: {{ .MetricsEndpoint | default "localhost:0" }}

  database:
    endpoints:
      {{- range .Endpoints.Database }}
      - {{ . }}
      {{- end }}

    username: "yugabyte"                       # The username for the database
    password: "yugabyte"                       # The password for the database
    database: {{ .DB.Name }}
    max-connections: 10                        # The maximum size of the connection pool
    min-connections: 5                         # The minimum size of the connection pool.

logging:
  development: true
  enabled: true
  level: INFO
