server:
  endpoint: {{ .ServerEndpoint | default "localhost:0" }}
  keep-alive:
    params:
      time: 300s
      timeout: 600s
    enforcement-policy:
      min-time: 60s
      permit-without-stream: false
monitoring:
  server:
    endpoint: {{ .MetricsEndpoint | default "localhost:0" }}

orderer:
  connection:
    endpoints:
      {{- range .Endpoints.Orderer }}
      - {{ . }}
      {{- end }}
  channel-id: {{ .ChannelID }}
  consensus-type: BFT
committer:
  endpoint: {{ .Endpoints.Coordinator }}

ledger:
  path: {{ .LedgerPath }}

last-committed-block-set-interval: 5s

bootstrap:
  genesis-block-file-path: {{ .ConfigBlockPath }}

logging:
  enabled: {{ .Logging.Enabled }}
  level: {{ .Logging.Level }}
  caller: {{ .Logging.Caller }}
  development: {{ .Logging.Development }}
  output: {{ .Logging.Output }}
  name: sidecar
