sig-verification:
  server:
    endpoint: {{ .ServerEndpoint | default "localhost:0" }}
  monitoring:
    server:
      endpoint: {{ .MetricsEndpoint | default "localhost:0" }}

  parallel-executor:
    parallelism: 40
    batch-time-cutoff: 10ms
    batch-size-cutoff: 50
    channel-buffer-size: 50

{{ template "loggingBlock" . }}
