#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Copy configs
  include: ../subtasks/copy-configs.yaml
  when: selected_hosts | d([]) | length > 0
- name: Edit orderer client config
  vars:
    config_dst_filepath: "{{dst_dir}}/{{hostvar_instance.inventory_hostname}}/{{hostvar_instance.config}}"
    inherit_peer: "{{hostvars[hostvar_instance.inherit_peer]}}"
  yedit:
    src: "{{config_dst_filepath}}"
    edits:
      - key: "{{config_root}}.channel-id"
        value: "{{channel_id}}"
      - key: "{{config_root}}.prometheus.endpoint"
        value: ":{{hostvar_instance.prometheus_exporter_port}}"
      - key: "{{config_root}}.orderer-connection-profile"
        value: "{{hostvar_instance.config_dir}}/fabric.{{topology_name}}/peers/{{inherit_peer.organization}}.{{inherit_peer.inventory_hostname}}/profile.yaml"
      - key: "{{config_root}}.prometheus.endpoint"
        value: ":{{hostvar_instance.prometheus_exporter_port}}"
  loop: "{{selected_hosts}}"
  loop_control:
    loop_var: hostvar_instance