#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Copy configs
  include: ./copy-configs.yaml
- name: Adapt endpoints
  vars:
    filename: "{{host_instance.config}}"
    endpoint: "{{config_item.endpoint | d(':%d' | format(host_instance.service_port | d(0)))}}"
    dst_filepath: "{{dst_dir}}/{{host_instance.inventory_hostname}}/{{filename}}"
    monitoring_host: "{{hostvars[groups['monitoring'][0]]}}"
  yedit:
    src: "{{dst_filepath}}"
    edits:
      - key: "{{config_root}}.server.endpoint"
        value: "{{endpoint}}"
      - key: "{{config_root}}.prometheus.endpoint"
        value: ":{{host_instance.prometheus_exporter_port}}"
      - key: "{{config_root}}.prometheus.latency-endpoint"
        value: "{{monitoring_host.ansible_host}}:{{monitoring_host.jaeger_exporter_port}}"
  loop: "{{selected_hosts}}"
  loop_control:
    loop_var: host_instance
