#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Edit config endpoints according to the inventory
  vars:
    filename: "{{hostvar_instance.config}}"
    hostvar_instance: "{{hostvars[host_instance]}}"
    config_root: "{{config_item.config_root}}"
    endpoint: "{{config_item.endpoint | d(':%d' | format(hostvar_instance.service_port | d(0)))}}"
    src_filepath: "{{src_dir}}{{filename}}"
    dst_filepath: "{{dst_dir}}{{host_instance}}-{{filename}}"
    monitoring_host: "{{hostvars[groups['monitoring'][0]]}}"
  include: ./create-base-vars-for-host-config.yaml
  loop: "{{groups[config_item.target_hosts] | default([])}}"
  loop_control:
    loop_var: host_instance
