#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Modify blockgen profile
  vars:
    small_txs: 1.0
    large_txs: 0.0
    invalidity_ratio: 0.0
    double_spends: 0.0
    block_size: 100
  yedit:
    src: "{{filepath}}"
    edits:
      - key: transaction.size
        append: true
        value:
          - value: 2
            probability: "{{small_txs}}"
          - value: 8
            probability: "{{large_txs}}"
      - key: conflicts.statistical.invalidsignature
        value: "{{invalidity_ratio}}"
      - key: conflicts.statistical.doublespends
        value: "{{double_spends}}"
      - key: block.size
        value: "{{block_size}}"