#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Adapt endpoints
  vars:
    committer: "{{groups['coordinators'] | default([]) | map('extract', hostvars) | first}}"
    committer_endpoint: "{{committer.ansible_host}}:{{committer.service_port}}"
    orderer: "{{groups['orderingservices'] | default([]) | map('extract', hostvars) | first}}"
    orderer_endpoint: "{{orderer.ansible_host}}:{{orderer.service_port}}"
  yedit:
    src: "{{filepath}}"
    edits:
      - key: sidecar.committer.endpoint
        value: "{{committer_endpoint}}"
      - key: sidecar.orderer.endpoint
        value: "{{orderer_endpoint}}"
      - key: sidecar.orderer.channel-id
        value: "{{channel_id}}"
