#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Kill process
  shell:
    cmd: lsof -i :{{process_port}} -sTCP:LISTEN |awk 'NR > 1 {print $2}'  |xargs kill -f -15
  when: process_port is defined
  ignore_errors: yes
  loop:
    - "{{service_port | d()}}"
    - "{{prometheus_exporter_port}}"
  loop_control:
    loop_var: process_port
- name: Runs server
  vars:
    session_name: "{{inventory_hostname}}"
    env_vars: "{{env | d([]) | join(' ')}}"
    options: "{{opts | d({}) | combine({} if config | d('') | length == 0 else {'configs': config_dir + inventory_hostname + '-' + config})}}"
    flags: "{{['--'] | product(options.keys() | d([])) | map('join') | zip(options.values() | d([])) | map('join', '=') | join(' ')}}"
  set_fact:
    command: tmux new-session -s {{session_name}} -d "{{env_vars}} {{binary_dir}}{{service_name}} {{flags}}"
- shell:
    cmd: "{{command}}"
  async: 10
  poll: 0
  register: stdout
  when: only_kill is undefined or only_kill == false
- debug:
    msg:
      - " {{command}}"
      - " {{stdout}}"
- set_fact:
    command: ""
- name: Wait until server is running
  vars:
    server_port: "{{hostvars[inventory_hostname].service_port | d()}}"
  wait_for:
    port: "{{server_port}}"
  when: (only_kill is undefined or only_kill == false) and (server_port != '')
