#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Kill process
  shell:
    cmd: lsof -i :{{process_port}} -sTCP:LISTEN |awk 'NR > 1 {print $2}'  |xargs kill -f -15
  when: process_port | d(0) | int > 0 and only_kill | d(0) == true
  ignore_errors: yes
  loop:
    - "{{service_port}}"
    - "{{prometheus_exporter_port}}"
  loop_control:
    loop_var: process_port
- name: Kill tmux
  shell:
    cmd: tmux kill-server
  when: only_kill is defined or only_kill == true
  ignore_errors: yes
- vars:
    var_prefix: "--"
    env_vars: "{{env | d([]) | join(' ')}}"
    flags: "{{[var_prefix] | product((options | d({})).keys() | d([])) | map('join') | zip((options | d({})).values() | d([])) | map('join', '=') | join(' ')}}"
  set_fact:
    command: "{{env_vars}} {{binary_dir}}{{service_name}} {{flags}}"
  when: service_name | d('') | length > 0
- vars:
    session_name: "{{inventory_hostname}}"
  set_fact:
    command: tmux new-session -s {{session_name}} -d "{{command}}"
  when: use_tmux | d(true) == true
- shell:
    cmd: "{{command}}"
  async: 10
  poll: 0
  register: stdout
  when: command | d('') | length > 0 and only_kill | d(false) == false
- debug:
    msg:
      - " {{command}}"
      - " {{stdout}}"
  when: command | d('') | length > 0
- set_fact:
    command: ""
- name: Wait until server is running
  vars:
    server_port: "{{hostvars[inventory_hostname].service_port | d(0)}}"
  wait_for:
    port: "{{server_port}}"
  when: command | d('') | length > 0 and only_kill | d(false) == false and wait_until_running | d(false) == true and server_port | d(0) | int > 0
