#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: "Transfer {{file_type}} for {{inventory_hostname}}"
  vars:
    src_dir: "{{orderer_artifacts_path}}/{{topology_dir}}"
    dst_dir: "{{config_dir}}"
    rsync_opts:
#      - --include='*/'
#      - "--include=**/{{topology_dir}}/{{node_type}}/**{{node_name}}**/{{hostvars[node_name][file_type]}}"
#      - --exclude='*'
      - --prune-empty-dirs
  include_tasks: ../subtasks/copy-file.yaml
- include_tasks: ./rename-config-files.yaml