#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: "Transfer idemix token creds to {{inventory_hostname}}"
  vars:
    src_dir: "{{orderer_artifacts_path}}/token"
    dst_dir: "{{config_dir}}"
    rsync_opts:
      - --include='*/'
      - "--include=**/token/crypto/*/{{path}}"
      - --exclude='*'
      - --prune-empty-dirs
  include_tasks: ../subtasks/copy-file.yaml
  when: path | length > 0
  loop:
    - "idemix/{{inventory_hostname}}*/msp/**"
    - "{{'issuer/**' if issuer_identities | d([]) | length > 0 else ''}}"
    - "{{'certifiers/**' if certifier | d(false) == true else ''}}"
    - "{{'auditor/**' if auditor | d(false) == true else ''}}"
  loop_control:
    loop_var: path
