#
# SPDX-License-Identifier: Apache-2.0
#
---
- stat:
    path: "{{orderer_artifacts_path}}/{{topology_dir}}/systemchannel_block.pb"
  register: result
- name: "Transfer genesis blocks for {{inventory_hostname}}, channels: {{channel_ids}}, system_channel: {{include_system_channel}}"
  vars:
    has_system_channel: "{{result.stat.isreg | d(false)}}"
    src_dir: "{{orderer_artifacts_path}}/{{topology_dir}}"
    dst_dir: "{{config_dir}}/{{topology_dir}}"
    tx_channel_blocks: "{{channel_ids | d([]) | product(['_tx.pb']) | map('join') | list if has_system_channel else []}}"
    tx_system_channel_blocks: "{{[] if has_system_channel else channel_ids | d([]) | product(['_block.pb']) | map('join') | list}}"
    system_channel_blocks: "{{['systemchannel_block.pb'] if include_system_channel | d(false) and has_system_channel else []}}"
  include_tasks: ../subtasks/copy-file.yaml
  loop: "{{tx_channel_blocks + tx_system_channel_blocks + system_channel_blocks}}"
  loop_control:
    loop_var: filename
  when: include_genesis | d(false) == true