#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: "Transfer {{file_type}} for {{inventory_hostname}}"
  vars:
    src_dir: "{{orderer_artifacts_path}}/fabric.{{topology_name}}"
    dst_dir: "{{config_dir}}"
    rsync_opts:
      - --include='*/'
      - "--include=**/fabric.{{topology_name}}/{{node_type}}/**{{node_name}}**/{{hostvars[node_name][file_type]}}"
      - --exclude='*'
      - --prune-empty-dirs
  include_tasks: ../subtasks/copy-file.yaml
- name: Find all files with extension .yaml under folder and all sub folders
  find:
    paths: "{{config_dir}}/fabric.{{topology_name}}"
    patterns: '*.yaml'
    recurse: yes
  register: files_to_change
- name: Replace <<SC_ROOT_DIR>> in files
  replace:
    dest: "{{ item.path }}"
    regexp: '<<SC_ROOT_DIR>>'
    replace: '{{config_dir}}'
  loop_control:
    label: "{{ item.path }}"
  with_items: "{{ files_to_change.files }}"