#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: "Transfer peer creds to {{inventory_hostname}}"
  vars:
    src_dir: "{{orderer_artifacts_path}}/{{topology_dir}}"
    dst_dir: "{{config_dir}}"
    rsync_opts:
#      - --include='*/'
#      - "--include=**/{{topology_dir}}/crypto/**/{{node_type}}/*{{node_domain}}/msp/**"
#      - --exclude='*'
      - --prune-empty-dirs
  include_tasks: ../subtasks/copy-file.yaml
  loop:
    - users
    - peers
  loop_control:
    loop_var: node_type