OrdererOrgs:
  - Name: orderer
    Domain: orderer.org
    EnableNodeOUs: true
    Specs:
      - Hostname: raft0
        SANS:
          - tokentestbed1.sl.cloud9.ibm.com
          - 0.0.0.0
          - localhost
      - Hostname: raft1
        SANS:
          - tokentestbed2.sl.cloud9.ibm.com
          - 0.0.0.0
          - localhost
      - Hostname: raft2
        SANS:
          - tokentestbed3.sl.cloud9.ibm.com
          - 0.0.0.0
          - localhost
      - Hostname: raft3
        SANS:
          - tokentestbed4.sl.cloud9.ibm.com
          - 0.0.0.0
          - localhost
      - Hostname: raft4
        SANS:
          - tokentestbed5.sl.cloud9.ibm.com
          - 0.0.0.0
          - localhost

PeerOrgs:
  - Name: org1
    Domain: org1.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - tokentestbed13.sl.cloud9.ibm.com
        - tokentestbed14.sl.cloud9.ibm.com
        - localhost
        - 0.0.0.0
    Users:
      Count: 1
