orderer-submitter:
  channel-id: mychannel
  orderers:
    - tokentestbed1.sl.cloud9.ibm.com:7050
  prometheus:
    endpoint: :2112
  orderer-connection-profile: /root/config/orderer-connection-profile.yaml
  messages: 5000000
  go-routines: 20
  message-size: 160
  signed: true
  orderer-type: BFT