sidecar:
  server:
    endpoint: :5050
    keep-alive:
      params:
        time: 300s
        timeout: 600s
      enforcement-policy:
        min-time: 60s
        permit-without-stream: false
  monitoring:
    metrics:
      endpoint: :2111

  orderer:
    # SC_SIDECAR_ORDERER_CONNECTION_ENDPOINTS="localhost:7777 localhost:8888"
    connection:
      endpoints:
        - :7050
    # SC_SIDECAR_ORDERER_CHANNEL_ID=someChannel
    channel-id: mychannel
    consensus-type: BFT

  committer:
    endpoint: localhost:5002
    ledger-path: /root/sc/ledger
    output-channel-capacity: 20

logging:
  development: true
  enabled: true
  level: INFO
