validator-committer-service:
  # Configuration for the server
  server:
    # The server's endpoint configuration
    endpoint: :5001
    # Credentials for the server
  database:
    host: "localhost" # The host of the database
    port: 5433 # The port of the database
    username: "yugabyte" # The username for the database
    # TODO: pass password via environment variable
    password: "yugabyte" # The password for the database
    database: "yugabyte" # The database name
    max-connections: 10 # The maximum size of the connection pool
    min-connections: 5 # The minimum size of the connection pool.
  # Resource limit configurations
  resource-limits:
    max-workers-for-preparer: 1 # Maximum number of workers for the preparer
    max-workers-for-validator: 1 # Maximum number of workers for the validator
    max-workers-for-committer: 20 # Maximum number of workers for the committer
    min-transaction-batch-size: 1
  monitoring:
    metrics:
      enable: true
      endpoint: :2113
logging:
  development: true
  enabled: true
  level: INFO
