coordinator-service:
  server:
    endpoint: {{ .CommonEndpoints.ServerEndpoint}}
  sign-verifier:
    server: 
      {{- range .SigVerifierEndpoints }}
      - endpoint: {{ . }}
      {{- end }}
  validator-committer:
    server: 
     {{- range .VCServiceEndpoints }}
      - endpoint: {{ . }}
      {{- end }}
  dependency-graph:
    num-of-local-dep-constructors: 1
    waiting-txs-limit: 10000
    num-of-workers-for-global-dep-manager: 1
    # Add monitoring configuration here if applicable
  per-channel-buffer-size-per-goroutine: 10

  monitoring:
    metrics:
      enable: true
      endpoint: {{ .CommonEndpoints.MetricsEndpoint }}

# For debugging, change the output to "xxx.log" and the level to "DEBUG"
logging:
  development: true
  enabled: true
  level: INFO
  output:
