mock-ordering-service:
  servers:
    - endpoint: {{ .ServerEndpoint }}
  block-size: {{ .BlockSize }}
  block-timeout: {{ .BlockTimeout }}
  config-block-path: {{ .ConfigBlockPath }}
  send-config-block: true
logging:
  Development: true
  enabled: true
  level: INFO
