sidecar:
  server:
    endpoint: {{ .CommonEndpoints.ServerEndpoint }}
    keep-alive:
      params:
        time: 300s
        timeout: 600s
      enforcement-policy:
        min-time: 60s
        permit-without-stream: false

  orderer:
    connection:
      endpoints:
        {{- range .OrdererEndpoints }}
        - {{ . }}
        {{- end }}
    channel-id: {{ .ChannelID }}
    consensus-type: BFT
  committer:
    endpoint: {{ .CoordinatorEndpoint }}

  ledger:
    path: {{ .LedgerPath }}

  monitoring:
    server:
      endpoint: {{ .CommonEndpoints.MetricsEndpoint }}

  bootstrap:
    genesis-block-file-path: {{ .ConfigBlockPath }}

logging:
  development: true
  enabled: true
  level: INFO
