sig-verification:
  server:
    endpoint: {{ .CommonEndpoints.ServerEndpoint }}
  monitoring:
    metrics:
      enable: true
      endpoint: {{ .CommonEndpoints.MetricsEndpoint }}

    latency:
      span-exporter: jaeger
      sampler:
        type: blocktx
        ratio: 10
        sample-size: 100
        sample-period: 100000
      endpoint: {{ .CommonEndpoints.LatencyEndpoint }}
      max-latency: 5s
      bucket-count: 1000
  scheme: "Ecdsa"

  parallel-executor:
    parallelism: 40
    batch-time-cutoff: 10ms
    batch-size-cutoff: 50
    channel-buffer-size: 50

logging:
  enabled: true
  level: INFO
  development: true
