validator-committer-service:
  server:
    endpoint: {{ .CommonEndpoints.ServerEndpoint }}

  database:
    endpoints:
      {{- range .DatabaseEndpoints }}
      - host: {{ .Host }}
        port: {{ .Port }}
      {{- end }}

    username: "yugabyte"
    # TODO: pass password via environment variable
    password: "yugabyte"
    database: {{ .DatabaseName }}
    max-connections: 10
    min-connections: 5
    load-balance: {{ .LoadBalance }}

  resource-limits:
    max-workers-for-preparer: 1
    max-workers-for-validator: 1
    max-workers-for-committer: 20
    min-transaction-batch-size: 1

  monitoring:
    server:
      endpoint: {{ .CommonEndpoints.MetricsEndpoint }}

logging:
  development: true
  enabled: true
  level: INFO
